import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const script = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "fusion-script-gate.js",
);

function run(stdin) {
  const input = typeof stdin === "string" ? stdin : JSON.stringify(stdin);
  return spawnSync(process.execPath, [script], { input, encoding: "utf8" });
}

const execute = (payload) => ({
  tool_name: "mcp__fusion__fusion_mcp_execute",
  tool_input: { featureType: "script", object: payload },
});

test("blocks every process-invoking construct, marker or not", () => {
  for (const fragment of [
    "import subprocess",
    "os.system('open -a Fusion')",
    "os.execv(path, args)",
    "os.popen('echo hi')",
    "os.spawnl(os.P_NOWAIT, exe)",
    "os.posix_spawn(exe, argv, env)",
    "import pty; pty.spawn(['sh'])",
    "from os import system",
    "from os import path, popen",
    "os . system('echo spaced')",
    "os\n  .\n  execv(path, args)",
    "from posix_things import posix_spawnp\nposix_spawnp(exe, argv, env)",
    "fork()",
    "import os as platform_api\nplatform_api.system('echo hi')",
    "from os import system as run_it",
    "__import__('os').system('echo hi')",
    "from multiprocessing import Pool",
    "Popen(['ls'])",
  ]) {
    const marked = `FUSION_DESIGN_REPORT_BEGIN\n${fragment}\n`;
    const result = run(execute({ script: marked }));
    assert.equal(result.status, 2, fragment);
    assert.match(result.stderr, /second Fusion instance/);
  }
});

test("ensurepip is blocked ad hoc but allowed in shipped lane transactions", () => {
  // The shipped capability probe imports ensurepip by name purely to report
  // whether the module exists; its emitted script carries the lane marker.
  const adhoc = run(execute({ script: "import ensurepip" }));
  assert.equal(adhoc.status, 2);
  const probe = run(
    execute({ script: 'REPORT_BEGIN = "FUSION_DESIGN_REPORT_BEGIN"\nimport ensurepip\n' }),
  );
  assert.equal(probe.status, 0);
});

test("blocks an oversized ad hoc script with an actionable message", () => {
  const monolith = Array.from({ length: 300 }, (_, i) => `x${i} = ${i}`).join("\n");
  const result = run(execute({ script: monolith }));
  assert.equal(result.status, 2);
  assert.match(result.stderr, /thin-transport bound/);
  assert.match(result.stderr, /one visible edit per snippet/);
  assert.match(result.stderr, /shipped lane tooling/);
});

test("exempts oversized scripts carrying the shipped emitters' marker shape", () => {
  // Pinned against real emitted output: the transaction prelude declares
  // REPORT_BEGIN (single-quoted, near the top), the bootstrap opens with its
  // header comment.
  const prelude =
    "import json\nimport os\nimport adsk.core\n\n" +
    "PROJECT_NAME = 'pod'\nMANIFEST_SHA256 = 'abc'\n" +
    "REPORT_BEGIN = 'FUSION_DESIGN_REPORT_BEGIN'\n";
  for (const head of [
    prelude,
    "# Generated by fusion-design; pass this source to Fusion's Python execution capability.\n",
  ]) {
    const long = head + "y = 1\n".repeat(400);
    const result = run(execute({ script: long }));
    assert.equal(result.status, 0, head.slice(0, 30));
  }
});

test("a forged marker buried mid-script exempts nothing", () => {
  const forged =
    "y = 1\n".repeat(400) +
    'note = "REPORT_BEGIN = \'FUSION_DESIGN_REPORT_BEGIN\'"\n';
  const result = run(execute({ script: forged }));
  assert.equal(result.status, 2);
  assert.match(result.stderr, /thin-transport bound/);
});

test("allows a small clean snippet silently", () => {
  const result = run(execute({ script: "import adsk.core\nprint('ok')" }));
  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
});

test("ignores non-fusion and non-execute tools and script-free calls", () => {
  for (const input of [
    { tool_name: "Bash", tool_input: { command: "subprocess" } },
    { tool_name: "mcp__fusion__fusion_mcp_read", tool_input: { queryType: "licensing" } },
    execute({ operation: "open" }),
  ]) {
    const result = run(input);
    assert.equal(result.status, 0);
  }
});

test("fails open with a DEGRADED note on unparseable input", () => {
  const result = run("not json {");
  assert.equal(result.status, 0);
  assert.match(result.stderr, /DEGRADED/);
});

test("reads a top-level tool_input.script too", () => {
  const result = run({
    tool_name: "mcp__fusion360__execute_script",
    tool_input: { script: "import subprocess" },
  });
  assert.equal(result.status, 2);
});
