import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const script = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "fusion-script-gate.js",
);

function run(stdin) {
  const input = typeof stdin === "string" ? stdin : JSON.stringify(stdin);
  return spawnSync(process.execPath, [script], { input, encoding: "utf8" });
}

const execute = (payload) => ({
  tool_name: "mcp__fusion__fusion_mcp_execute",
  tool_input: { featureType: "script", object: payload },
});

test("blocks every process-invoking construct, marker or not", () => {
  for (const fragment of [
    "import subprocess",
    "os.system('open -a Fusion')",
    "os.execv(path, args)",
    "from multiprocessing import Pool",
    "Popen(['ls'])",
  ]) {
    const marked = `FUSION_DESIGN_REPORT_BEGIN\n${fragment}\n`;
    const result = run(execute({ script: marked }));
    assert.equal(result.status, 2, fragment);
    assert.match(result.stderr, /second Fusion instance/);
  }
});

test("ensurepip is blocked ad hoc but allowed in shipped lane transactions", () => {
  // The shipped capability probe imports ensurepip by name purely to report
  // whether the module exists; its emitted script carries the lane marker.
  const adhoc = run(execute({ script: "import ensurepip" }));
  assert.equal(adhoc.status, 2);
  const probe = run(
    execute({ script: 'REPORT_BEGIN = "FUSION_DESIGN_REPORT_BEGIN"\nimport ensurepip\n' }),
  );
  assert.equal(probe.status, 0);
});

test("blocks an oversized ad hoc script with an actionable message", () => {
  const monolith = Array.from({ length: 300 }, (_, i) => `x${i} = ${i}`).join("\n");
  const result = run(execute({ script: monolith }));
  assert.equal(result.status, 2);
  assert.match(result.stderr, /thin-transport bound/);
  assert.match(result.stderr, /one visible edit per snippet/);
  assert.match(result.stderr, /shipped lane tooling/);
});

test("exempts oversized scripts carrying the shipped lane markers", () => {
  for (const marker of [
    'REPORT_BEGIN = "FUSION_DESIGN_REPORT_BEGIN"',
    "# via _script_prelude",
    "# Generated by fusion-design; pass this source to Fusion",
  ]) {
    const long = marker + "\n" + "y = 1\n".repeat(400);
    const result = run(execute({ script: long }));
    assert.equal(result.status, 0, marker);
  }
});

test("allows a small clean snippet silently", () => {
  const result = run(execute({ script: "import adsk.core\nprint('ok')" }));
  assert.equal(result.status, 0);
  assert.equal(result.stderr, "");
});

test("ignores non-fusion and non-execute tools and script-free calls", () => {
  for (const input of [
    { tool_name: "Bash", tool_input: { command: "subprocess" } },
    { tool_name: "mcp__fusion__fusion_mcp_read", tool_input: { queryType: "licensing" } },
    execute({ operation: "open" }),
  ]) {
    const result = run(input);
    assert.equal(result.status, 0);
  }
});

test("fails open with a DEGRADED note on unparseable input", () => {
  const result = run("not json {");
  assert.equal(result.status, 0);
  assert.match(result.stderr, /DEGRADED/);
});

test("reads a top-level tool_input.script too", () => {
  const result = run({
    tool_name: "mcp__fusion360__execute_script",
    tool_input: { script: "import subprocess" },
  });
  assert.equal(result.status, 2);
});
