"""Conservative, streaming observations of G-code tool-selection commands."""

from __future__ import annotations

from pathlib import Path
import re
from typing import Any


MAX_LINE_BYTES = 64 * 1024
MAX_TOOL_EVENTS = 10_000
MAX_ACTIVE_TOOLS = 256
MAX_TOOL_ID = 2**31 - 1

_TOOL_LINE = re.compile(r"^\s*T(?P<tool>[0-9]+)\s*(?:;.*)?$")
_FLAVOR_LINE = re.compile(
    r"^\s*;\s*(?:FLAVOR|gcode_flavor)\s*[:=]\s*(?P<flavor>[A-Za-z0-9_.-]+)\s*$",
    re.IGNORECASE,
)
_GENERATED_LINE = re.compile(r"^\s*;\s*generated by\s+(?P<producer>[^\s;]+)", re.IGNORECASE)

# These text flavors use the ordinary T<number> tool-selection command. A
# marker outside this set is not enough evidence to claim the metric.
_TEXT_FLAVORS = {
    "grbl",
    "klipper",
    "mach3",
    "makerware",
    "marlin",
    "marlin2",
    "reprap",
    "repetier",
    "smoothie",
    "sprinter",
    "teacup",
}
_PRUSA_PRODUCERS = {"prusaslicer", "superslicer"}


def _empty_result(*, available: bool, reason: str | None = None, flavor: str | None = None) -> dict[str, Any]:
    return {
        "available": available,
        "reason": reason,
        "flavor": flavor,
        "tool_events": [],
        "tool_event_count": 0,
        "tool_events_truncated": False,
        "active_tools": [] if available else None,
        "tool_change_count": 0 if available else None,
    }


def audit_gcode(
    gcode_path: str | Path,
) -> dict[str, Any]:
    """Audit complete ``T<number>`` lines without loading the G-code file.

    Only a whole line whose command is exactly ``T<number>`` (optionally
    surrounded by whitespace and followed by a ``;`` comment) is an event.
    A final line without a newline is complete once EOF is reached.
    """
    events: list[dict[str, int]] = []
    active_tools: set[int] = set()
    transitions = 0
    previous_tool: int | None = None
    line_number = 0
    flavor: str | None = None
    producer: str | None = None
    unavailable_reason: str | None = None
    tool_event_count = 0
    overlong_line_seen = False

    def process(line: bytes) -> None:
        nonlocal line_number, flavor, producer, unavailable_reason
        nonlocal transitions, previous_tool, tool_event_count
        line_number += 1
        text = line.decode("utf-8", errors="replace").rstrip("\r")

        flavor_match = _FLAVOR_LINE.match(text)
        if flavor_match:
            marker = flavor_match.group("flavor").lower()
            if marker not in _TEXT_FLAVORS:
                unavailable_reason = f"Unsupported G-code flavor marker {marker!r}."
            elif flavor is not None and flavor != marker:
                unavailable_reason = f"Conflicting G-code flavor markers {flavor!r} and {marker!r}."
            else:
                flavor = marker

        generated_match = _GENERATED_LINE.match(text)
        if generated_match:
            marker = generated_match.group("producer").lower()
            if marker not in _PRUSA_PRODUCERS:
                unavailable_reason = f"G-code producer {marker!r} is not a recognized Prusa text flavor."
            elif producer is not None and producer != marker:
                unavailable_reason = f"Conflicting G-code producers {producer!r} and {marker!r}."
            else:
                producer = marker

        match = _TOOL_LINE.match(text)
        if not match:
            return
        digits = match.group("tool")
        maximum = str(MAX_TOOL_ID)
        if len(digits) > len(maximum) or (len(digits) == len(maximum) and digits > maximum):
            unavailable_reason = f"Tool identifier exceeds the supported maximum {MAX_TOOL_ID}."
            return
        tool = int(digits)
        if tool not in active_tools and len(active_tools) >= MAX_ACTIVE_TOOLS:
            unavailable_reason = f"More than {MAX_ACTIVE_TOOLS} distinct active tools were observed."
            return
        tool_event_count += 1
        if len(events) < MAX_TOOL_EVENTS:
            events.append({"line": line_number, "tool": tool})
        active_tools.add(tool)
        if previous_tool is not None and previous_tool != tool:
            transitions += 1
        previous_tool = tool

    with Path(gcode_path).open("rb") as handle:
        while raw_line := handle.readline(MAX_LINE_BYTES + 1):
            if len(raw_line) > MAX_LINE_BYTES:
                while raw_line and not raw_line.endswith(b"\n"):
                    raw_line = handle.readline(MAX_LINE_BYTES + 1)
                line_number += 1
                overlong_line_seen = True
                continue
            process(raw_line.rstrip(b"\n"))

    if overlong_line_seen:
        return _empty_result(
            available=False,
            reason=f"A G-code line exceeded the {MAX_LINE_BYTES}-byte audit limit.",
            flavor=flavor,
        )
    if unavailable_reason:
        return _empty_result(available=False, reason=unavailable_reason, flavor=flavor)
    if flavor is None and producer is None:
        return _empty_result(
            available=False,
            reason="No recognized G-code flavor or producer marker was found.",
        )

    result = _empty_result(available=True, flavor=flavor or "standard_prusa_text")
    result["tool_events"] = events
    result["tool_event_count"] = tool_event_count
    result["tool_events_truncated"] = tool_event_count > len(events)
    result["active_tools"] = sorted(active_tools)
    result["tool_change_count"] = transitions
    return result
