"""Headless PrusaSlicer invocation, kept apart from project construction.

This is the *only* module in the package that starts a process. Project
construction (``prusaslicer_project.build_project`` and everything it calls)
stays free of any process-execution API, and its test enforces that; slicing
lives here so the boundary is a file boundary rather than a promise.

The lesson this module encodes:

    PrusaSlicer does not segfault on headless slicing. It segfaults when it is
    handed an *incomplete profile set*. ``--printer-profile`` alone exits 139
    (SIGSEGV) with no output; ``--printer-profile`` + ``--print-profile`` +
    ``--material-profile`` together with ``--datadir`` slices cleanly and
    writes valid G-code. ``PrusaSlicer --help`` says so outright: "To load
    configuration from profiles, you need to set whole banch of presets".

So the adapter refuses to invoke the binary with a partial set (that refusal is
``require_complete_profile_set``), and otherwise runs it and reports what the
produced G-code actually says.

What the guard does *not* need to check, measured against PrusaSlicer 2.9.6 on
2026-08-19: a **complete but unresolvable** set does not crash. Three names that
resolve to nothing, with and without ``--datadir``, both exit 1 with "Error while
loading config from profiles: Printer profile 'X' wasn't found." -- a clean,
named diagnostic this module already surfaces as a structured failure. The
SIGSEGV is specific to a *partial* set, so completeness, not resolvability, is
the property worth refusing on. ``--datadir`` is still required rather than
optional, because omitting it resolves the names against a configuration that
never validated them.

Statistics are only ever read out of the G-code, and only out of *whole lines* of
its trailing summary block -- the contiguous run of ``; key = value`` comments that
ends the file, ahead of the ``prusaslicer_config`` dump (``summary_block``). That
shape, not the size of the window we happened to read, is what keeps a profile's
custom *start* G-code out: the start G-code sits at the top of the file, separated
from the trailing run by the extrusion moves, so it is excluded whether the file is
200 bytes or 200 megabytes.

G-code can be hundreds of megabytes, so the file is read through a bounded head and
tail window, and both windows are trimmed to line boundaries before parsing --
a window cut mid-line turns a truncated number into a syntactically valid, wrong
one (``; total filament used [g] = 41.9`` cut at ``4`` reads as ``4.0``). The head
window is used only for the slicer version banner. A run whose window yielded no
statistics at all is a failure, never an ``ok: true`` report with an empty
statistics block.

``--binary-gcode=0`` is forced: the Original Prusa XL presets default to binary
G-code, whose statistics are not readable as ``; `` comments. We want the
numbers, not a print file, so ASCII is requested explicitly.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path
import re
import subprocess
import tempfile
from types import SimpleNamespace
from typing import Any, Callable

from .gcode_audit import audit_gcode
from .prusaslicer_project import ResolvedPresets
from .prusaslicer_runtime import (
    BUNDLE_EXECUTABLE,
    PATH_EXECUTABLE_NAMES,
    resolve_executable,
    runtime_fingerprint,
    sha256_file,
)


# Every one of these must be present before the binary is invoked. A partial set
# is the documented cause of the SIGSEGV, so it is refused, never attempted.
REQUIRED_PROFILE_KINDS = ("printer", "print", "filament")

PROFILE_FLAGS = {
    "printer": "--printer-profile",
    "print": "--print-profile",
    "filament": "--material-profile",
}

DEFAULT_TIMEOUT_SECONDS = 900
MAX_PROCESS_OUTPUT_BYTES = 4 * 1024 * 1024

# The head window carries the "generated by" banner and nothing else we trust.
# The statistics block sits at the end, ahead of the prusaslicer_config dump; a
# full dump for a multi-tool printer runs past 128 KiB, so the tail is sized to
# clear one. Past this the statistics fall outside the window, and that is
# reported as a failure rather than as an empty statistics block.
_HEAD_BYTES = 8 * 1024
_TAIL_BYTES = 1024 * 1024

# PrusaSlicer's profile dump. It sits after the statistics block and is itself a
# run of "; key = value" lines, so the summary scan has to stop at it.
_CONFIG_BEGIN = "; prusaslicer_config = begin"

# The full evidence chain a project built by build_project can supply. Only
# project_sha256 is required here -- it is the one this module can actually check
# against a file it holds -- so the report states whether the rest arrived rather
# than implying a completeness it never verified.
CHAIN_BINDING_KEYS = (
    "project_sha256",
    "export_index_sha256",
    "manifest_sha256",
    "verification_report_sha256",
    "export_run_id",
)

_SHA256_RE = re.compile(r"\A[0-9a-f]{64}\Z")
_VERSION_PATTERN = re.compile(r"^;\s*generated by (?P<version>PrusaSlicer [^\s]+)", re.MULTILINE)
_WARNING_PATTERN = re.compile(r"\b(warning|error|failed|cannot)\b", re.IGNORECASE)

_RUNTIME_EVIDENCE_KEYS = (
    "version",
    "executable",
    "executable_sha256",
    "datadir",
    "profile_snapshot_sha256",
)
_RUNTIME_FINGERPRINT_KEYS = (
    "executable",
    "executable_sha256",
    "datadir",
    "profile_snapshot_sha256",
)

# label -> (gcode comment key, kind). "vector" values are per-extruder.
_STATISTIC_KEYS = {
    "filament_used_mm": ("filament used [mm]", "vector"),
    "filament_used_cm3": ("filament used [cm3]", "vector"),
    "filament_used_g": ("filament used [g]", "vector"),
    "total_filament_used_g": ("total filament used [g]", "scalar"),
    "estimated_printing_time_normal": ("estimated printing time (normal mode)", "text"),
    "estimated_printing_time_silent": ("estimated printing time (silent mode)", "text"),
}


class IncompleteProfileSetError(ValueError):
    """Raised instead of invoking PrusaSlicer with a partial profile set."""


def require_complete_profile_set(presets: ResolvedPresets | dict[str, Any]) -> dict[str, str]:
    """Return the printer/print/filament identifiers, or refuse before executing anything.

    This is the guard the whole module exists around: PrusaSlicer segfaults when
    it is given some but not all of the presets, so a partial set never reaches
    ``subprocess`` at all.
    """
    if isinstance(presets, ResolvedPresets):
        mapping: dict[str, Any] = presets.as_dict()
    elif isinstance(presets, dict):
        mapping = presets
    else:
        raise IncompleteProfileSetError(
            "presets must be a ResolvedPresets or a mapping of printer/print/filament preset names."
        )
    complete: dict[str, str] = {}
    missing: list[str] = []
    for kind in REQUIRED_PROFILE_KINDS:
        name = mapping.get(kind)
        name = name.strip() if isinstance(name, str) else ""
        if name:
            complete[kind] = name
        else:
            missing.append(kind)
    if missing:
        raise IncompleteProfileSetError(
            f"Refusing to run PrusaSlicer with an incomplete profile set: missing "
            f"{', '.join(missing)}. PrusaSlicer exits 139 (SIGSEGV) with no output when only part "
            "of the printer/print/filament set is supplied -- 'To load configuration from profiles, "
            "you need to set whole banch of presets' (PrusaSlicer --help)."
        )
    return complete


def slice_command(
    executable: Path,
    project_path: Path,
    profiles: dict[str, str],
    gcode_path: Path,
    datadir: str | Path | None,
) -> list[str]:
    """The exact argv used. An argument list -- never a shell string."""
    command = [str(executable), "--export-gcode"]
    if datadir is not None:
        command += ["--datadir", str(datadir)]
    for kind in REQUIRED_PROFILE_KINDS:
        command += [PROFILE_FLAGS[kind], profiles[kind]]
    command += ["--binary-gcode=0", "--output", str(gcode_path), str(project_path)]
    return command


def _tail(text: str, limit: int = 4000) -> str:
    text = text.strip()
    return text if len(text) <= limit else "..." + text[-limit + 3 :]


def _bounded_file_tail(handle: Any, limit: int = MAX_PROCESS_OUTPUT_BYTES) -> tuple[str, bool]:
    size = handle.seek(0, 2)
    handle.seek(max(0, size - limit))
    value = handle.read()
    if isinstance(value, bytes):
        value = value.decode("utf-8", errors="replace")
    return str(value), size > limit


def _run_process(
    command: list[str],
    *,
    timeout: float,
    runner: Callable[..., Any],
) -> Any:
    if runner is not subprocess.run:
        completed = runner(
            command,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
            shell=False,
        )
        stdout = getattr(completed, "stdout", "") or ""
        stderr = getattr(completed, "stderr", "") or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode("utf-8", errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode("utf-8", errors="replace")
        return SimpleNamespace(
            returncode=getattr(completed, "returncode", 0),
            stdout=str(stdout),
            stderr=str(stderr),
            stdout_truncated=False,
            stderr_truncated=False,
        )
    with tempfile.TemporaryFile() as stdout_file, tempfile.TemporaryFile() as stderr_file:
        try:
            completed = runner(
                command,
                stdout=stdout_file,
                stderr=stderr_file,
                timeout=timeout,
                check=False,
                shell=False,
            )
        except subprocess.TimeoutExpired as error:
            stdout, _ = _bounded_file_tail(stdout_file)
            stderr, _ = _bounded_file_tail(stderr_file)
            raise subprocess.TimeoutExpired(error.cmd, error.timeout, output=stdout, stderr=stderr) from error
        stdout, stdout_truncated = _bounded_file_tail(stdout_file)
        stderr, stderr_truncated = _bounded_file_tail(stderr_file)
    return SimpleNamespace(
        returncode=completed.returncode,
        stdout=stdout,
        stderr=stderr,
        stdout_truncated=stdout_truncated,
        stderr_truncated=stderr_truncated,
    )


def _numbers(raw: str) -> list[float] | None:
    values: list[float] = []
    for chunk in raw.split(","):
        try:
            value = float(chunk.strip())
        except ValueError:
            return None
        if not math.isfinite(value):
            return None
        values.append(value)
    return values or None


def summary_block(text: str) -> list[str]:
    """The trailing run of ``; key = value`` comments PrusaSlicer writes its stats in.

    PrusaSlicer emits the statistics as one contiguous comment block at the very
    end of the G-code, after the end G-code and before the ``prusaslicer_config``
    dump. Anchoring on that shape is what keeps a profile's *custom start* G-code
    out: it sits at the top of the file, separated from the trailing run by the
    extrusion moves, so it can never be part of the run no matter how small the
    file is. Selecting the tail *window* is not the same guarantee -- for a G-code
    under the window size the whole file is the window, and the start G-code is in
    it.
    """
    lines = text.splitlines()
    # The config dump follows the summary and is itself "; key = value" shaped.
    for index in range(len(lines) - 1, -1, -1):
        if lines[index].startswith(_CONFIG_BEGIN):
            lines = lines[:index]
            break
    end = len(lines)
    while end and not lines[end - 1].strip():
        end -= 1
    start = end
    while start and lines[start - 1].startswith(";") and "=" in lines[start - 1]:
        start -= 1
    return lines[start:end]


def parse_gcode_statistics(text: str) -> tuple[dict[str, Any], list[str]]:
    """Read statistics out of the G-code's trailing summary block.

    Absent is reported, never guessed, and a stats-shaped comment anywhere outside
    that block -- custom start G-code above all -- is not a measurement.
    """
    found: dict[str, str] = {}
    for line in summary_block(text):
        key, _, value = line[1:].partition("=")
        found[key.strip()] = value.strip()

    statistics: dict[str, Any] = {}
    absent: list[str] = []
    for label, (comment_key, kind) in _STATISTIC_KEYS.items():
        raw = found.get(comment_key)
        if raw is None or not raw:
            absent.append(label)
            continue
        if kind == "text":
            statistics[label] = raw
            continue
        values = _numbers(raw)
        if values is None:
            absent.append(label)
        elif kind == "scalar":
            statistics[label] = values[0]
        else:
            statistics[label] = values
            statistics[f"{label}_total"] = round(sum(values), 6)
    return statistics, sorted(absent)


def _whole_lines(window: bytes, *, drop_leading: bool, drop_trailing: bool) -> bytes:
    """Trim a byte window to the lines it holds completely.

    A window boundary lands at an arbitrary byte. Parsing the partial line it
    leaves behind is how a real 41.9 g becomes a reported 4.0 g, so the partial
    line is discarded rather than completed.
    """
    if drop_leading:
        newline = window.find(b"\n")
        window = window[newline + 1 :] if newline >= 0 else b""
    if drop_trailing:
        newline = window.rfind(b"\n")
        window = window[: newline + 1] if newline >= 0 else b""
    return window


def _read_gcode_evidence(gcode_path: Path) -> dict[str, Any]:
    digest = hashlib.sha256()
    size = 0
    head = b""
    tail = b""
    with gcode_path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
            size += len(chunk)
            if len(head) < _HEAD_BYTES:
                head += chunk[: _HEAD_BYTES - len(head)]
            tail = (tail + chunk)[-_TAIL_BYTES:]

    truncated = size > _TAIL_BYTES
    # The tail is where the summary block lives; summary_block() is what actually
    # confines parsing to it, so this window choice is an efficiency bound, not the
    # guarantee. See summary_block.
    tail_text = _whole_lines(tail, drop_leading=truncated, drop_trailing=False).decode(
        "utf-8", errors="replace"
    )
    head_text = _whole_lines(head, drop_leading=False, drop_trailing=size > _HEAD_BYTES).decode(
        "utf-8", errors="replace"
    )
    statistics, absent = parse_gcode_statistics(tail_text)
    version_match = _VERSION_PATTERN.search(head_text) or _VERSION_PATTERN.search(tail_text)
    return {
        "gcode_path": str(gcode_path),
        "gcode_sha256": digest.hexdigest(),
        "gcode_byte_size": size,
        "slicer_version": version_match.group("version") if version_match else None,
        "statistics": statistics,
        "absent_statistics": absent,
        # Stated so a report where the statistics fell outside the window is
        # distinguishable from one where the slicer wrote none.
        "gcode_window": {
            "head_bytes": len(head),
            "tail_bytes": len(tail),
            "whole_file_read": not truncated,
        },
    }


def _checked_bindings(project: Path, bindings: dict[str, Any]) -> dict[str, Any]:
    """Confirm the file on disk is the project the caller says it is.

    Without this the slice hashes whatever is at the path and reports statistics
    under that hash, bound to nothing -- two different 64-char hashes could sit
    side by side in one report and still exit 0.
    """
    if not isinstance(bindings, dict):
        raise ValueError("bindings must be a mapping carrying at least project_sha256.")
    expected = bindings.get("project_sha256")
    if not isinstance(expected, str) or not _SHA256_RE.fullmatch(expected):
        raise ValueError(
            f"bindings['project_sha256'] is {expected!r}; a lowercase hex SHA-256 of the project "
            "being sliced is required, so the statistics attach to a known project."
        )
    actual = sha256_file(project)
    if actual != expected:
        raise ValueError(
            f"Project {str(project)!r} hashes to {actual}; the caller bound {expected}. The file "
            "changed between building the project and slicing it."
        )
    for key in CHAIN_BINDING_KEYS:
        if key == "project_sha256" or key not in bindings:
            continue
        value = bindings[key]
        if key.endswith("_sha256") and (not isinstance(value, str) or not _SHA256_RE.fullmatch(value)):
            raise ValueError(f"bindings[{key!r}] must be a lowercase hex SHA-256 when supplied.")
        if key == "export_run_id" and (not isinstance(value, str) or not value.strip()):
            raise ValueError("bindings['export_run_id'] must be a non-empty string when supplied.")
    return {key: value for key, value in bindings.items() if value is not None}


def _project_changed_during_slice(project: Path, expected: str) -> str | None:
    """Re-hash after the run: PrusaSlicer reopened the path we only checked before.

    Narrow, but the pre-run check and the slicer's own open are two reads of one
    path. A mismatch means the statistics describe a file that is no longer the
    one bound, so it is a failure rather than a footnote.
    """
    actual = sha256_file(project)
    return None if actual == expected else actual


def _runtime_evidence_drift(
    expected: dict[str, Any],
    actual: dict[str, Any],
) -> dict[str, dict[str, Any]]:
    return {
        key: {"expected": expected.get(key), "actual": actual.get(key)}
        for key in _RUNTIME_FINGERPRINT_KEYS
        if expected.get(key) != actual.get(key)
    }


def _checked_runtime_evidence(runtime_evidence: dict[str, Any] | None) -> dict[str, Any] | None:
    if runtime_evidence is None:
        return None
    if not isinstance(runtime_evidence, dict):
        raise ValueError("runtime_evidence must be a mapping from the authoritative PrusaSlicer query.")
    missing = [
        key
        for key in _RUNTIME_EVIDENCE_KEYS
        if not isinstance(runtime_evidence.get(key), str) or not runtime_evidence[key].strip()
    ]
    for key in ("executable_sha256", "profile_snapshot_sha256"):
        value = runtime_evidence.get(key)
        if isinstance(value, str) and not _SHA256_RE.fullmatch(value):
            missing.append(key)
    if missing:
        names = ", ".join(dict.fromkeys(missing))
        raise ValueError(f"runtime_evidence is missing required fields: {names}.")
    return dict(runtime_evidence)


def slice_project(
    project_path: str | Path,
    presets: ResolvedPresets | dict[str, Any],
    *,
    bindings: dict[str, Any],
    executable: str | Path | None = None,
    datadir: str | Path | None = None,
    runtime_evidence: dict[str, Any] | None = None,
    timeout: float = DEFAULT_TIMEOUT_SECONDS,
    runner: Callable[..., Any] = subprocess.run,
) -> dict[str, Any]:
    """Slice ``project_path`` headlessly and report G-code statistics as evidence.

    Fails closed: a non-zero exit (139/SIGSEGV included), a timeout, or a missing
    output file yields a structured failure naming the exit status and stderr
    tail. It never raises past the caller with the diagnostics lost, and never
    reports a statistic that did not come out of the produced G-code.

    ``bindings`` must carry the ``project_sha256`` the caller expects the file to
    have, and normally the rest of the chain the project came from
    (``manifest_sha256``, ``export_index_sha256``, ``verification_report_sha256``,
    ``export_run_id``). The hash is checked against the file before anything runs
    and the whole mapping is echoed into the result, so a slice block cannot be
    re-attributed to a project or a verification run it did not come from.

    Raises ``IncompleteProfileSetError`` *before* executing anything when the
    printer/print/filament set is incomplete -- that partial set is what makes
    PrusaSlicer crash.
    """
    profiles = require_complete_profile_set(presets)
    checked_runtime = _checked_runtime_evidence(runtime_evidence)

    project = Path(project_path).expanduser()
    if not project.is_file():
        raise ValueError(f"Project {str(project)!r} is not a file.")
    checked_bindings = _checked_bindings(project, bindings)

    if datadir is None and isinstance(presets, ResolvedPresets):
        # The presets were resolved against this root; slicing anywhere else
        # would look them up in a configuration that never validated them.
        datadir = presets.config_root
    if datadir is None:
        # A plain-dict caller used to silently drop --datadir, so the names were
        # looked up in PrusaSlicer's default configuration -- which may hold a
        # different preset under the same name than the one that was validated.
        raise ValueError(
            "A datadir is required: pass a ResolvedPresets (which carries the configuration root "
            "its names were validated against) or an explicit datadir. Without one PrusaSlicer "
            "resolves the preset names in a configuration nothing here checked."
        )
    datadir_path = Path(datadir).expanduser()
    if not datadir_path.is_absolute():
        raise ValueError(f"datadir must be an absolute path; got {datadir!r}.")
    if isinstance(timeout, bool) or not isinstance(timeout, (int, float)) or not math.isfinite(float(timeout)) or timeout <= 0:
        raise ValueError("timeout must be a finite number greater than zero")
    datadir = str(datadir_path)

    binary = resolve_executable(executable)
    base: dict[str, Any] = {
        "supported": True,
        "attempted": False,
        "ok": False,
        "project_path": str(project),
        "project_sha256": checked_bindings["project_sha256"],
        "bindings": checked_bindings,
        "chain_complete": all(checked_bindings.get(key) is not None for key in CHAIN_BINDING_KEYS),
        "presets": dict(profiles),
        "datadir": str(datadir) if datadir is not None else None,
    }
    if checked_runtime is not None:
        base["runtime_evidence"] = checked_runtime
    if binary is None:
        return {
            **base,
            "reason": (
                "No PrusaSlicer executable was found: no explicit path was given, "
                f"{str(BUNDLE_EXECUTABLE)!r} does not exist, and none of "
                f"{', '.join(PATH_EXECUTABLE_NAMES)} is on PATH."
            ),
        }

    gcode_path = project.with_suffix(".gcode")
    if gcode_path.exists() or gcode_path.is_symlink():
        raise ValueError(f"Refusing to overwrite existing G-code {str(gcode_path)!r}.")

    command = slice_command(binary, project, profiles, gcode_path, datadir)
    base = {**base, "attempted": True, "executable": str(binary), "command": command}

    runtime_before: dict[str, Any] | None = None
    if checked_runtime is not None:
        runtime_before = runtime_fingerprint(binary, datadir)
        base["runtime_fingerprint_before"] = runtime_before
        drift = _runtime_evidence_drift(checked_runtime, runtime_before)
        if drift:
            return {
                **base,
                "attempted": False,
                "outcome": "snapshot_changed",
                "runtime_fingerprint_before": runtime_before,
                "drift": drift,
                "failure": "PrusaSlicer executable or profile datadir changed before slicing.",
            }

    try:
        completed = _run_process(command, timeout=float(timeout), runner=runner)
    except subprocess.TimeoutExpired as error:
        runtime_after = runtime_fingerprint(binary, datadir) if checked_runtime is not None else None
        drift = _runtime_evidence_drift(checked_runtime, runtime_after) if checked_runtime is not None else {}
        if runtime_after is not None:
            base["runtime_fingerprint_after"] = runtime_after
        gcode_path.unlink(missing_ok=True)
        if drift:
            return {
                **base,
                "exit_code": None,
                "outcome": "snapshot_changed",
                "runtime_fingerprint_before": runtime_before,
                "runtime_fingerprint_after": runtime_after,
                "drift": drift,
                "failure": "PrusaSlicer executable or profile datadir changed during slicing.",
                "stderr_tail": _tail(str(getattr(error, "stderr", "") or "")),
            }
        return {
            **base,
            "exit_code": None,
            "failure": f"PrusaSlicer did not finish within {timeout} seconds and was terminated.",
            "stderr_tail": _tail(str(getattr(error, "stderr", "") or "")),
        }
    except OSError as error:
        runtime_after = runtime_fingerprint(binary, datadir) if checked_runtime is not None else None
        drift = _runtime_evidence_drift(checked_runtime, runtime_after) if checked_runtime is not None else {}
        if runtime_after is not None:
            base["runtime_fingerprint_after"] = runtime_after
        gcode_path.unlink(missing_ok=True)
        if drift:
            return {
                **base,
                "exit_code": None,
                "outcome": "snapshot_changed",
                "runtime_fingerprint_before": runtime_before,
                "runtime_fingerprint_after": runtime_after,
                "drift": drift,
                "failure": "PrusaSlicer executable or profile datadir changed during slicing.",
                "stderr_tail": "",
            }
        return {**base, "exit_code": None, "failure": f"PrusaSlicer could not be executed: {error}", "stderr_tail": ""}

    exit_code = int(completed.returncode)
    stderr = completed.stderr or ""
    stdout = completed.stdout or ""
    runtime_after = runtime_fingerprint(binary, datadir) if checked_runtime is not None else None
    drift = _runtime_evidence_drift(checked_runtime, runtime_after) if checked_runtime is not None else {}
    if runtime_after is not None:
        base["runtime_fingerprint_after"] = runtime_after
    if drift:
        gcode_path.unlink(missing_ok=True)
        return {
            **base,
            "exit_code": exit_code,
            "outcome": "snapshot_changed",
            "runtime_fingerprint_before": runtime_before,
            "runtime_fingerprint_after": runtime_after,
            "drift": drift,
            "failure": "PrusaSlicer executable or profile datadir changed during slicing.",
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }
    if exit_code != 0:
        gcode_path.unlink(missing_ok=True)
        crash = " (SIGSEGV)" if exit_code == -11 else ""
        return {
            **base,
            "exit_code": exit_code,
            "failure": f"PrusaSlicer exited {exit_code}{crash} without producing usable G-code.",
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }
    if not gcode_path.is_file():
        return {
            **base,
            "exit_code": exit_code,
            "failure": f"PrusaSlicer exited 0 but wrote no G-code at {str(gcode_path)!r}.",
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }

    warnings = [
        _tail(line.strip())
        for line in (stdout + "\n" + stderr).splitlines()
        if line.strip() and _WARNING_PATTERN.search(line)
    ]
    changed = _project_changed_during_slice(project, checked_bindings["project_sha256"])
    if changed is not None:
        gcode_path.unlink(missing_ok=True)
        return {
            **base,
            "exit_code": exit_code,
            "warnings": warnings,
            "failure": (
                f"Project {str(project)!r} hashes to {changed} after the slice; the caller bound "
                f"{checked_bindings['project_sha256']}. The file changed while PrusaSlicer was "
                "reading it, so these statistics describe a project this report cannot name."
            ),
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }
    try:
        evidence = _read_gcode_evidence(gcode_path)
    except (OSError, ValueError) as error:
        gcode_path.unlink(missing_ok=True)
        return {
            **base,
            "exit_code": exit_code,
            "warnings": warnings,
            "failure": f"Unable to read G-code evidence: {error}",
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }
    if not evidence["statistics"]:
        # An empty statistics block reads as "the slicer reported nothing". It is
        # indistinguishable from "the statistics were outside the window we read",
        # so neither is allowed to look like success.
        window = evidence["gcode_window"]
        gcode_path.unlink(missing_ok=True)
        return {
            **base,
            "exit_code": exit_code,
            "warnings": warnings,
            "failure": (
                f"PrusaSlicer exited 0 but no statistic was readable from the "
                f"{window['tail_bytes']}-byte tail window of a {evidence['gcode_byte_size']}-byte "
                "G-code. Nothing here is estimated, so no statistics are reported."
                + ("" if window["whole_file_read"] else " The G-code was larger than the window.")
            ),
            "stderr_tail": _tail(stderr) or _tail(stdout),
            **evidence,
        }
    try:
        audit = audit_gcode(gcode_path)
        audit_sha256 = sha256_file(gcode_path)
    except (OSError, ValueError) as error:
        gcode_path.unlink(missing_ok=True)
        return {
            **base,
            "exit_code": exit_code,
            "warnings": warnings,
            "failure": f"Unable to audit G-code evidence: {error}",
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }
    if audit_sha256 != evidence["gcode_sha256"]:
        gcode_path.unlink(missing_ok=True)
        return {
            **base,
            "exit_code": exit_code,
            "warnings": warnings,
            "failure": "G-code changed while evidence and tool audit were being read; refusing to bind mixed bytes.",
            "stderr_tail": _tail(stderr) or _tail(stdout),
            "gcode_sha256_before_audit": evidence["gcode_sha256"],
            "gcode_sha256_after_audit": audit_sha256,
        }
    result = {
        **base,
        "ok": True,
        "exit_code": exit_code,
        "warnings": warnings,
        "stdout_tail": _tail(stdout),
        "stderr_tail": _tail(stderr),
        **evidence,
        "gcode_audit": audit,
    }
    if runtime_before is not None:
        result["runtime_fingerprint_before"] = runtime_before
        result["runtime_fingerprint_after"] = runtime_after
    return result
