"""Headless PrusaSlicer invocation, kept apart from project construction.

This is the *only* module in the package that starts a process. Project
construction (``prusaslicer_project.build_project`` and everything it calls)
stays free of any process-execution API, and its test enforces that; slicing
lives here so the boundary is a file boundary rather than a promise.

The lesson this module encodes:

    PrusaSlicer does not segfault on headless slicing. It segfaults when it is
    handed an *incomplete profile set*. ``--printer-profile`` alone exits 139
    (SIGSEGV) with no output; ``--printer-profile`` + ``--print-profile`` +
    ``--material-profile`` together with ``--datadir`` slices cleanly and
    writes valid G-code. ``PrusaSlicer --help`` says so outright: "To load
    configuration from profiles, you need to set whole banch of presets".

So the adapter refuses to invoke the binary with a partial set (that refusal is
``require_complete_profile_set``), and otherwise runs it and reports what the
produced G-code actually says. Statistics are only ever read out of the G-code;
nothing here estimates, interpolates, or infers a number.

``--binary-gcode=0`` is forced: the Original Prusa XL presets default to binary
G-code, whose statistics are not readable as ``; `` comments. We want the
numbers, not a print file, so ASCII is requested explicitly.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
import re
import shutil
import subprocess
from typing import Any, Callable

from .prusaslicer_project import ResolvedPresets


# Every one of these must be present before the binary is invoked. A partial set
# is the documented cause of the SIGSEGV, so it is refused, never attempted.
REQUIRED_PROFILE_KINDS = ("printer", "print", "filament")

PROFILE_FLAGS = {
    "printer": "--printer-profile",
    "print": "--print-profile",
    "filament": "--material-profile",
}

# Checked only when no explicit path is given, and only as one candidate among
# several -- never as the sole option.
BUNDLE_EXECUTABLE = Path("/Applications/Original Prusa Drivers/PrusaSlicer.app/Contents/MacOS/PrusaSlicer")
PATH_EXECUTABLE_NAMES = ("prusa-slicer", "PrusaSlicer")

DEFAULT_TIMEOUT_SECONDS = 900

# Statistics live in the first and last few KB of the G-code; the middle is
# extrusion moves and can be hundreds of megabytes.
_HEAD_BYTES = 8 * 1024
_TAIL_BYTES = 128 * 1024

_VERSION_PATTERN = re.compile(r"^;\s*generated by (?P<version>PrusaSlicer [^\s]+)", re.MULTILINE)
_WARNING_PATTERN = re.compile(r"\b(warning|error|failed|cannot)\b", re.IGNORECASE)

# label -> (gcode comment key, kind). "vector" values are per-extruder.
_STATISTIC_KEYS = {
    "filament_used_mm": ("filament used [mm]", "vector"),
    "filament_used_cm3": ("filament used [cm3]", "vector"),
    "filament_used_g": ("filament used [g]", "vector"),
    "total_filament_used_g": ("total filament used [g]", "scalar"),
    "estimated_printing_time_normal": ("estimated printing time (normal mode)", "text"),
    "estimated_printing_time_silent": ("estimated printing time (silent mode)", "text"),
}


class IncompleteProfileSetError(ValueError):
    """Raised instead of invoking PrusaSlicer with a partial profile set."""


def require_complete_profile_set(presets: ResolvedPresets | dict[str, Any]) -> dict[str, str]:
    """Return the printer/print/filament identifiers, or refuse before executing anything.

    This is the guard the whole module exists around: PrusaSlicer segfaults when
    it is given some but not all of the presets, so a partial set never reaches
    ``subprocess`` at all.
    """
    if isinstance(presets, ResolvedPresets):
        mapping: dict[str, Any] = presets.as_dict()
    elif isinstance(presets, dict):
        mapping = presets
    else:
        raise IncompleteProfileSetError(
            "presets must be a ResolvedPresets or a mapping of printer/print/filament preset names."
        )
    complete: dict[str, str] = {}
    missing: list[str] = []
    for kind in REQUIRED_PROFILE_KINDS:
        name = mapping.get(kind)
        name = name.strip() if isinstance(name, str) else ""
        if name:
            complete[kind] = name
        else:
            missing.append(kind)
    if missing:
        raise IncompleteProfileSetError(
            f"Refusing to run PrusaSlicer with an incomplete profile set: missing "
            f"{', '.join(missing)}. PrusaSlicer exits 139 (SIGSEGV) with no output when only part "
            "of the printer/print/filament set is supplied -- 'To load configuration from profiles, "
            "you need to set whole banch of presets' (PrusaSlicer --help)."
        )
    return complete


def resolve_executable(explicit: str | Path | None = None) -> Path | None:
    """Find the PrusaSlicer binary: explicit path, then app bundle, then ``PATH``."""
    if explicit is not None:
        candidate = Path(explicit).expanduser()
        return candidate if candidate.is_file() else None
    if BUNDLE_EXECUTABLE.is_file():
        return BUNDLE_EXECUTABLE
    for name in PATH_EXECUTABLE_NAMES:
        found = shutil.which(name)
        if found:
            return Path(found)
    return None


def slice_command(
    executable: Path,
    project_path: Path,
    profiles: dict[str, str],
    gcode_path: Path,
    datadir: str | Path | None,
) -> list[str]:
    """The exact argv used. An argument list -- never a shell string."""
    command = [str(executable), "--export-gcode"]
    if datadir is not None:
        command += ["--datadir", str(datadir)]
    for kind in REQUIRED_PROFILE_KINDS:
        command += [PROFILE_FLAGS[kind], profiles[kind]]
    command += ["--binary-gcode=0", "--output", str(gcode_path), str(project_path)]
    return command


def _tail(text: str, limit: int = 4000) -> str:
    text = text.strip()
    return text if len(text) <= limit else "..." + text[-limit:]


def _numbers(raw: str) -> list[float] | None:
    values: list[float] = []
    for chunk in raw.split(","):
        try:
            values.append(float(chunk.strip()))
        except ValueError:
            return None
    return values or None


def parse_gcode_statistics(text: str) -> tuple[dict[str, Any], list[str]]:
    """Read statistics out of G-code comments. Absent is reported, never guessed."""
    found: dict[str, str] = {}
    for line in text.splitlines():
        if not line.startswith(";") or "=" not in line:
            continue
        key, _, value = line[1:].partition("=")
        found[key.strip()] = value.strip()

    statistics: dict[str, Any] = {}
    absent: list[str] = []
    for label, (comment_key, kind) in _STATISTIC_KEYS.items():
        raw = found.get(comment_key)
        if raw is None or not raw:
            absent.append(label)
            continue
        if kind == "text":
            statistics[label] = raw
            continue
        values = _numbers(raw)
        if values is None:
            absent.append(label)
        elif kind == "scalar":
            statistics[label] = values[0]
        else:
            statistics[label] = values
            statistics[f"{label}_total"] = round(sum(values), 6)
    return statistics, sorted(absent)


def _read_gcode_evidence(gcode_path: Path) -> dict[str, Any]:
    digest = hashlib.sha256()
    size = 0
    head = b""
    tail = b""
    with gcode_path.open("rb") as handle:
        while chunk := handle.read(1024 * 1024):
            digest.update(chunk)
            size += len(chunk)
            if len(head) < _HEAD_BYTES:
                head += chunk[: _HEAD_BYTES - len(head)]
            tail = (tail + chunk)[-_TAIL_BYTES:]
    text = (head + b"\n" + tail).decode("utf-8", errors="replace")
    statistics, absent = parse_gcode_statistics(text)
    version_match = _VERSION_PATTERN.search(text)
    return {
        "gcode_path": str(gcode_path),
        "gcode_sha256": digest.hexdigest(),
        "gcode_byte_size": size,
        "slicer_version": version_match.group("version") if version_match else None,
        "statistics": statistics,
        "absent_statistics": absent,
    }


def slice_project(
    project_path: str | Path,
    presets: ResolvedPresets | dict[str, Any],
    *,
    executable: str | Path | None = None,
    datadir: str | Path | None = None,
    timeout: float = DEFAULT_TIMEOUT_SECONDS,
    runner: Callable[..., Any] = subprocess.run,
) -> dict[str, Any]:
    """Slice ``project_path`` headlessly and report G-code statistics as evidence.

    Fails closed: a non-zero exit (139/SIGSEGV included), a timeout, or a missing
    output file yields a structured failure naming the exit status and stderr
    tail. It never raises past the caller with the diagnostics lost, and never
    reports a statistic that did not come out of the produced G-code.

    Raises ``IncompleteProfileSetError`` *before* executing anything when the
    printer/print/filament set is incomplete -- that partial set is what makes
    PrusaSlicer crash.
    """
    profiles = require_complete_profile_set(presets)

    project = Path(project_path).expanduser()
    if not project.is_file():
        raise ValueError(f"Project {str(project)!r} is not a file.")

    if datadir is None and isinstance(presets, ResolvedPresets):
        # The presets were resolved against this root; slicing anywhere else
        # would look them up in a configuration that never validated them.
        datadir = presets.config_root

    binary = resolve_executable(executable)
    base: dict[str, Any] = {
        "supported": True,
        "attempted": False,
        "ok": False,
        "project_path": str(project),
        "project_sha256": hashlib.sha256(project.read_bytes()).hexdigest(),
        "presets": dict(profiles),
        "datadir": str(datadir) if datadir is not None else None,
    }
    if binary is None:
        return {
            **base,
            "reason": (
                "No PrusaSlicer executable was found: no explicit path was given, "
                f"{str(BUNDLE_EXECUTABLE)!r} does not exist, and none of "
                f"{', '.join(PATH_EXECUTABLE_NAMES)} is on PATH."
            ),
        }

    gcode_path = project.with_suffix(".gcode")
    if gcode_path.exists() or gcode_path.is_symlink():
        raise ValueError(f"Refusing to overwrite existing G-code {str(gcode_path)!r}.")

    command = slice_command(binary, project, profiles, gcode_path, datadir)
    base = {**base, "attempted": True, "executable": str(binary), "command": command}

    try:
        completed = runner(command, capture_output=True, text=True, timeout=timeout, check=False)
    except subprocess.TimeoutExpired:
        gcode_path.unlink(missing_ok=True)
        return {
            **base,
            "exit_code": None,
            "failure": f"PrusaSlicer did not finish within {timeout} seconds and was terminated.",
            "stderr_tail": "",
        }
    except OSError as error:
        gcode_path.unlink(missing_ok=True)
        return {**base, "exit_code": None, "failure": f"PrusaSlicer could not be executed: {error}", "stderr_tail": ""}

    exit_code = int(completed.returncode)
    stderr = completed.stderr or ""
    stdout = completed.stdout or ""
    if exit_code != 0:
        gcode_path.unlink(missing_ok=True)
        crash = " (SIGSEGV)" if exit_code in (139, -11) else ""
        return {
            **base,
            "exit_code": exit_code,
            "failure": f"PrusaSlicer exited {exit_code}{crash} without producing usable G-code.",
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }
    if not gcode_path.is_file():
        return {
            **base,
            "exit_code": exit_code,
            "failure": f"PrusaSlicer exited 0 but wrote no G-code at {str(gcode_path)!r}.",
            "stderr_tail": _tail(stderr) or _tail(stdout),
        }

    warnings = [
        line.strip()
        for line in (stdout + "\n" + stderr).splitlines()
        if line.strip() and _WARNING_PATTERN.search(line)
    ]
    return {**base, "ok": True, "exit_code": exit_code, "warnings": warnings, **_read_gcode_evidence(gcode_path)}
