"""Emit one base-Fusion heat-set-insert boss transaction."""

import json
from collections.abc import Mapping, Sequence

from .contracts import BossRequest


RESULT_BEGIN = "FUSION_ENCLOSURE_FEATURE_RESULT_BEGIN"
RESULT_END = "FUSION_ENCLOSURE_FEATURE_RESULT_END"


def _payload_literal(payload: object) -> str:
    return repr(json.dumps(payload, sort_keys=True, separators=(",", ":")))


def emit_create_boss_source(request: BossRequest) -> str:
    payload = _payload_literal(request.to_payload())
    return f'''# Generated by fusion-design enclosure-feature boss.heat_set_insert/v1
import json
import adsk.core
import adsk.fusion

REQUEST = json.loads({payload})
ATTRIBUTE_GROUP = "fusion_parametric_design"
RESULT_BEGIN = "{RESULT_BEGIN}"
RESULT_END = "{RESULT_END}"


def _refuse(token, message):
    raise RuntimeError(token + ": " + message)


def _resolve(design, spec):
    entities = design.findEntityByToken(spec["entity_token"])
    if len(entities) != 1:
        _refuse("target-not-found" if not entities else "ambiguous-target", spec["entity_token"])
    entity = entities[0]
    if getattr(entity, "assemblyContext", None):
        _refuse("participant-body-ambiguity", "v1 requires native component entities, not occurrence proxies")
    if entity.objectType != spec["expected_type"]:
        _refuse("invalid-selection-type", entity.objectType + " != " + spec["expected_type"])
    actual_path = _component_path(design, entity)
    if actual_path != spec["component_path"]:
        _refuse("participant-body-ambiguity", actual_path + " != " + spec["component_path"])
    return entity


def _component(entity):
    component = getattr(entity, "parentComponent", None)
    if component:
        return component
    body = getattr(entity, "body", None)
    if body:
        return body.parentComponent
    sketch = getattr(entity, "parentSketch", None)
    if sketch:
        return sketch.parentComponent
    _refuse("invalid-selection-type", entity.objectType + " has no component ownership")


def _component_path(design, entity):
    occurrence = getattr(entity, "assemblyContext", None)
    if occurrence:
        return occurrence.fullPathName
    component = _component(entity)
    return "Root" if component == design.rootComponent else component.name


def _same_entity(left, right):
    return left == right or getattr(left, "nativeObject", left) == getattr(right, "nativeObject", right)


def _stamp(entity, role):
    values = {{
        "kind": "enclosure_feature",
        "feature_instance_id": REQUEST["feature_id"],
        "recipe_id": REQUEST["recipe_id"],
        "recipe_version": str(REQUEST["recipe_version"]),
        "feature_role": role,
        "parameter_namespace": REQUEST["parameter_namespace"],
    }}
    for name, value in values.items():
        if not entity.attributes.add(ATTRIBUTE_GROUP, name, value):
            _refuse("feature-create-failed", "could not stamp " + role + "." + name)


def _parameter(design, spec, created):
    if design.userParameters.itemByName(spec["name"]):
        _refuse("parameter-name-conflict", spec["name"])
    value = adsk.core.ValueInput.createByString(spec["expression"])
    parameter = design.userParameters.add(
        spec["name"], value, spec["units"],
        spec["evidence_class"] + ("; " + spec["source_ref"] if spec["source_ref"] else ""),
    )
    if not parameter:
        _refuse("invalid-parameter-expression", spec["name"])
    created.append(parameter)
    _stamp(parameter, "parameter_" + spec["semantic_name"])
    return parameter


def _point(entity):
    point = getattr(entity, "worldGeometry", None) or getattr(entity, "geometry", None)
    if point is None:
        _refuse("invalid-selection-type", "placement has no point geometry")
    return point


def _circle(design, sketch, centre, radius_expression, diameter_parameter):
    radius = design.unitsManager.evaluateExpression(radius_expression, "mm") / 2.0
    circle = sketch.sketchCurves.sketchCircles.addByCenterRadius(centre, radius)
    text = adsk.core.Point3D.create(centre.x + radius, centre.y, 0.0)
    dimension = sketch.sketchDimensions.addDiameterDimension(circle, text)
    dimension.parameter.expression = diameter_parameter
    return circle


def _participant(input_, target):
    if not hasattr(input_, "participantBodies"):
        _refuse("participant-body-ambiguity", "this Fusion build cannot scope the operation")
    input_.participantBodies = [target]


def _token(entity):
    token = getattr(entity, "entityToken", None)
    if not token:
        _refuse("feature-create-failed", "created entity has no token")
    return token


def _cleanup(created):
    failures = []
    for entity in reversed(created):
        try:
            if getattr(entity, "isValid", True):
                group = adsk.fusion.TimelineGroup.cast(entity)
                deleted = group.deleteMe(True) if group else entity.deleteMe()
                if not deleted:
                    failures.append(getattr(entity, "name", entity.objectType))
        except Exception as error:
            failures.append(getattr(entity, "name", type(entity).__name__) + ": " + str(error))
    return failures


def _dimension_rectangle(sketch, lines, horizontal, length_name, thickness_name):
    length_line = None
    thickness_line = None
    count = getattr(lines, "count", None)
    count = len(lines) if count is None else count
    for index in range(count):
        line = lines.item(index) if hasattr(lines, "item") else lines[index]
        start = line.startSketchPoint.geometry
        end = line.endSketchPoint.geometry
        if abs(end.x - start.x) >= abs(end.y - start.y):
            if (horizontal and length_line is None) or (not horizontal and thickness_line is None):
                target = "length"
            else:
                target = "thickness"
            orientation = adsk.fusion.DimensionOrientations.HorizontalDimensionOrientation
        else:
            if (horizontal and thickness_line is None) or (not horizontal and length_line is None):
                target = "thickness"
            else:
                target = "length"
            orientation = adsk.fusion.DimensionOrientations.VerticalDimensionOrientation
        if target == "length" and length_line is None:
            length_line = (line, orientation)
        elif target == "thickness" and thickness_line is None:
            thickness_line = (line, orientation)
    if not length_line or not thickness_line:
        _refuse("feature-create-failed", "could not identify gusset rectangle edges")
    for line, orientation, expression in (
        (*length_line, "2 * " + length_name),
        (*thickness_line, thickness_name),
    ):
        start = line.startSketchPoint.geometry
        end = line.endSketchPoint.geometry
        text = adsk.core.Point3D.create((start.x + end.x) / 2.0, (start.y + end.y) / 2.0, 0.0)
        dimension = sketch.sketchDimensions.addDistanceDimension(
            line.startSketchPoint, line.endSketchPoint, orientation, text
        )
        dimension.parameter.expression = expression


def _gusset_sketch(design, component, support_plane, placement, parameters, horizontal, created):
    sketch = component.sketches.add(support_plane)
    created.append(sketch)
    axis = "Horizontal" if horizontal else "Vertical"
    sketch.name = REQUEST["instance_name"] + " - " + axis + " Gussets"
    centre = sketch.modelToSketchSpace(_point(placement))
    half_length = design.unitsManager.evaluateExpression(parameters["rib_length"].name, "mm")
    half_thickness = design.unitsManager.evaluateExpression(parameters["rib_thickness"].name, "mm") / 2.0
    corner = adsk.core.Point3D.create(
        centre.x + (half_length if horizontal else half_thickness),
        centre.y + (half_thickness if horizontal else half_length),
        0.0,
    )
    lines = sketch.sketchCurves.sketchLines.addCenterPointRectangle(centre, corner)
    _dimension_rectangle(
        sketch,
        lines,
        horizontal,
        parameters["rib_length"].name,
        parameters["rib_thickness"].name,
    )
    return sketch


def _join_sketch(component, target, sketch, distance_name, name, created):
    extrude_input = component.features.extrudeFeatures.createInput(
        sketch.profiles.item(0), adsk.fusion.FeatureOperations.NewBodyFeatureOperation
    )
    extrude_input.setDistanceExtent(False, adsk.core.ValueInput.createByString(distance_name))
    feature = component.features.extrudeFeatures.add(extrude_input)
    if not feature:
        _refuse("feature-create-failed", "Fusion did not create " + name)
    created.append(feature)
    feature.name = name + " Tool"
    tool_bodies = adsk.core.ObjectCollection.create()
    tool_bodies.add(feature.bodies.item(0))
    combine_input = component.features.combineFeatures.createInput(target, tool_bodies)
    combine_input.operation = adsk.fusion.FeatureOperations.JoinFeatureOperation
    combine_input.isKeepToolBodies = False
    combine = component.features.combineFeatures.add(combine_input)
    if not combine:
        _refuse("feature-create-failed", "Fusion did not join " + name)
    created.append(combine)
    combine.name = name
    return feature, combine


def _build(app, design, target, support, placement, created):
    component = target.parentComponent
    if not _same_entity(support.body, target) or support.body.parentComponent != component:
        _refuse("participant-body-ambiguity", "support face is not owned by the target body")
    if _component(placement) != component:
        _refuse("participant-body-ambiguity", "placement is not owned by the target component")
    start_index = design.timeline.count
    managed = []
    plane_input = component.constructionPlanes.createInput()
    plane_input.setByOffset(support, adsk.core.ValueInput.createByString("0 mm"))
    support_plane = component.constructionPlanes.add(plane_input)
    if not support_plane:
        _refuse("feature-create-failed", "Fusion did not create the managed support plane")
    created.append(support_plane)
    support_plane.name = REQUEST["instance_name"] + " - Support Plane"
    managed.append((support_plane, "support_plane"))
    parameters = {{}}
    for item in REQUEST["parameters"]:
        parameter = _parameter(design, item, created)
        parameters[item["semantic_name"]] = parameter
    values = {{
        name: design.unitsManager.evaluateExpression(parameter.name, "mm")
        for name, parameter in parameters.items()
    }}
    if any(value <= 0 for value in values.values()):
        _refuse("insufficient-wall-thickness", "all boss dimensions must be positive")
    if not values["outer_diameter"] > values["head_seat_diameter"] > values["bore_diameter"]:
        _refuse("insufficient-wall-thickness", "outer diameter must exceed head seat and bore diameters")
    if values["bore_depth"] > values["boss_height"]:
        _refuse("insufficient-wall-thickness", "insert bore depth exceeds the boss height")
    if values["head_seat_depth"] >= values["boss_height"]:
        _refuse("insufficient-wall-thickness", "head seat depth must be less than boss height")
    if values["bore_depth"] + values["head_seat_depth"] < values["boss_height"]:
        _refuse("insufficient-wall-thickness", "bore and head seat must form one continuous passage")
    if REQUEST["rib_count"]:
        if values["rib_length"] <= values["outer_diameter"] / 2.0:
            _refuse("insufficient-wall-thickness", "gusset length must extend beyond the boss radius")

    outer_sketch = component.sketches.add(support_plane)
    created.append(outer_sketch)
    outer_sketch.name = REQUEST["instance_name"] + " - Boss Profile"
    centre = outer_sketch.modelToSketchSpace(_point(placement))
    _circle(
        design,
        outer_sketch,
        centre,
        parameters["outer_diameter"].expression,
        parameters["outer_diameter"].name,
    )
    outer_feature_input = component.features.extrudeFeatures.createInput(
        outer_sketch.profiles.item(0), adsk.fusion.FeatureOperations.NewBodyFeatureOperation
    )
    outer_feature_input.setDistanceExtent(
        False, adsk.core.ValueInput.createByString(parameters["boss_height"].name)
    )
    outer_feature = component.features.extrudeFeatures.add(outer_feature_input)
    if not outer_feature:
        _refuse("feature-create-failed", "Fusion did not create the boss extrusion")
    created.append(outer_feature)
    outer_feature.name = REQUEST["instance_name"] + " - Boss Tool"
    tool_bodies = adsk.core.ObjectCollection.create()
    tool_bodies.add(outer_feature.bodies.item(0))
    combine_input = component.features.combineFeatures.createInput(target, tool_bodies)
    combine_input.operation = adsk.fusion.FeatureOperations.JoinFeatureOperation
    combine_input.isKeepToolBodies = False
    combine_feature = component.features.combineFeatures.add(combine_input)
    if not combine_feature:
        _refuse("feature-create-failed", "Fusion did not join the boss to the explicit target")
    created.append(combine_feature)
    combine_feature.name = REQUEST["instance_name"] + " - Boss Outer"
    managed.extend((
        (outer_sketch, "boss_profile"),
        (outer_feature, "boss_tool"),
        (combine_feature, "boss_outer"),
    ))
    adsk.doEvents()
    if adsk.fusion.Design.cast(app.activeProduct) != design:
        _refuse("feature-create-failed", "the active design changed during the transaction")

    if REQUEST["rib_count"]:
        for horizontal, role in ((True, "horizontal"), (False, "vertical")):
            gusset_sketch = _gusset_sketch(
                design, component, support_plane, placement, parameters, horizontal, created
            )
            gusset_feature, gusset_combine = _join_sketch(
                component,
                target,
                gusset_sketch,
                parameters["boss_height"].name,
                REQUEST["instance_name"] + " - " + role.title() + " Gussets",
                created,
            )
            managed.extend((
                (gusset_sketch, role + "_gusset_profile"),
                (gusset_feature, role + "_gusset_tool"),
                (gusset_combine, role + "_gusset_join"),
            ))

    bore_sketch = component.sketches.add(support_plane)
    created.append(bore_sketch)
    bore_sketch.name = REQUEST["instance_name"] + " - Insert Bore Profile"
    bore_centre = bore_sketch.modelToSketchSpace(_point(placement))
    _circle(
        design,
        bore_sketch,
        bore_centre,
        parameters["bore_diameter"].expression,
        parameters["bore_diameter"].name,
    )
    bore_feature_input = component.features.extrudeFeatures.createInput(
        bore_sketch.profiles.item(0), adsk.fusion.FeatureOperations.CutFeatureOperation
    )
    _participant(bore_feature_input, target)
    bore_feature_input.setDistanceExtent(
        False, adsk.core.ValueInput.createByString(parameters["bore_depth"].name)
    )
    bore_feature = component.features.extrudeFeatures.add(bore_feature_input)
    if not bore_feature:
        _refuse("feature-create-failed", "Fusion did not create the insert bore")
    created.append(bore_feature)
    bore_feature.name = REQUEST["instance_name"] + " - Insert Bore"
    managed.extend(((bore_sketch, "bore_profile"), (bore_feature, "insert_bore")))

    seat_sketch = component.sketches.add(support_plane)
    created.append(seat_sketch)
    seat_sketch.name = REQUEST["instance_name"] + " - Socket Head Seat Profile"
    seat_centre = seat_sketch.modelToSketchSpace(_point(placement))
    _circle(
        design,
        seat_sketch,
        seat_centre,
        parameters["head_seat_diameter"].expression,
        parameters["head_seat_diameter"].name,
    )
    seat_input = component.features.extrudeFeatures.createInput(
        seat_sketch.profiles.item(0), adsk.fusion.FeatureOperations.CutFeatureOperation
    )
    _participant(seat_input, target)
    seat_input.startExtent = adsk.fusion.OffsetStartDefinition.create(
        adsk.core.ValueInput.createByString(
            parameters["boss_height"].name + " - " + parameters["head_seat_depth"].name
        )
    )
    seat_input.setDistanceExtent(
        False, adsk.core.ValueInput.createByString(parameters["head_seat_depth"].name)
    )
    seat_feature = component.features.extrudeFeatures.add(seat_input)
    if not seat_feature:
        _refuse("feature-create-failed", "Fusion did not create the socket-head seat")
    created.append(seat_feature)
    seat_feature.name = REQUEST["instance_name"] + " - Socket Head Seat"
    managed.extend(((seat_sketch, "head_seat_profile"), (seat_feature, "head_seat")))

    for entity, role in managed:
        _stamp(entity, role)
    adsk.doEvents()
    if not design.computeAll():
        _refuse("timeline-unhealthy", "Compute All failed")
    adsk.doEvents()
    for feature, role in managed:
        if not hasattr(feature, "healthState"):
            continue
        if feature.healthState == adsk.fusion.FeatureHealthStates.ErrorFeatureHealthState:
            _refuse("timeline-unhealthy", feature.errorOrWarningMessage)
    if not target.isSolid:
        _refuse("body-not-solid", target.name)
    end_index = design.timeline.count - 1
    group = design.timeline.timelineGroups.add(start_index, end_index)
    if group:
        created.append(group)
        group.name = REQUEST["instance_name"] + " - Enclosure Feature"
    else:
        _refuse("feature-create-failed", "Fusion did not create the timeline group")
    return {{
        "status": "created",
        "feature_id": REQUEST["feature_id"],
        "recipe_id": REQUEST["recipe_id"],
        "recipe_version": REQUEST["recipe_version"],
        "parameter_names": [item.name for item in parameters.values()],
        "timeline_group_name": group.name,
        "native_objects": [
            {{
                "role": role,
                "name": entity.name,
                "token": _token(entity),
                "object_type": entity.objectType,
            }}
            for entity, role in managed
        ],
        "observations": {{"target_body": target.name, "target_is_solid": bool(target.isSolid)}},
        "invalidated_by": REQUEST["invalidated_by"],
        "claims_not_made": REQUEST["claims_not_made"],
        "warnings": ["insert and head-seat dimensions remain coupon-sensitive"],
    }}


def run(_context: str):
    app = adsk.core.Application.get()
    design = adsk.fusion.Design.cast(app.activeProduct)
    if not design or design.designType != adsk.fusion.DesignTypes.ParametricDesignType:
        _refuse("invalid-design-type", "a saved parametric design is required")
    if not app.activeDocument or not app.activeDocument.dataFile:
        _refuse("unsaved-document", "save the working design before creating managed features")
    target = _resolve(design, REQUEST["target_body"])
    support = _resolve(design, REQUEST["support_face"])
    placement = _resolve(design, REQUEST["placement"])
    created = []
    try:
        result = _build(app, design, target, support, placement, created)
    except Exception as error:
        cleanup_failures = _cleanup(created)
        if cleanup_failures:
            raise RuntimeError(
                "rollback-incomplete: " + str(error) + "; remaining=" + ", ".join(cleanup_failures)
            ) from error
        raise
    print(RESULT_BEGIN)
    print(json.dumps(result, sort_keys=True, separators=(",", ":")))
    print(RESULT_END)
'''


def emit_edit_feature_source(
    feature_id: str,
    updates: Mapping[str, str],
    parameter_names: Sequence[str],
    object_tokens: Sequence[str],
    timeline_group_name: str,
) -> str:
    payload = _lifecycle_payload(
        feature_id, parameter_names, object_tokens, timeline_group_name, updates
    )
    return _lifecycle_source("edit", payload)


def emit_inspect_feature_source(
    feature_id: str,
    parameter_names: Sequence[str],
    object_tokens: Sequence[str],
    timeline_group_name: str,
) -> str:
    payload = _lifecycle_payload(feature_id, parameter_names, object_tokens, timeline_group_name)
    return _lifecycle_source("inspect", payload)


def emit_delete_feature_source(
    feature_id: str,
    parameter_names: Sequence[str],
    object_tokens: Sequence[str],
    timeline_group_name: str,
) -> str:
    payload = _lifecycle_payload(feature_id, parameter_names, object_tokens, timeline_group_name)
    return _lifecycle_source("delete", payload)


def _lifecycle_payload(
    feature_id: str,
    parameter_names: Sequence[str],
    object_tokens: Sequence[str],
    timeline_group_name: str,
    updates: Mapping[str, str] | None = None,
) -> str:
    payload: dict[str, object] = {
        "feature_id": feature_id,
        "parameter_names": list(parameter_names),
        "object_tokens": list(object_tokens),
        "timeline_group_name": timeline_group_name,
    }
    if updates is not None:
        payload["updates"] = dict(updates)
    return _payload_literal(payload)


def _lifecycle_source(operation: str, payload: str) -> str:
    return f'''# Generated by fusion-design enclosure-feature lifecycle/v1
import json
import adsk.core
import adsk.fusion

REQUEST = json.loads({payload})
OPERATION = {operation!r}
ATTRIBUTE_GROUP = "fusion_parametric_design"
RESULT_BEGIN = "{RESULT_BEGIN}"
RESULT_END = "{RESULT_END}"
BASE_ROLES = {{
    "support_plane", "boss_profile", "boss_tool", "boss_outer",
    "bore_profile", "insert_bore", "head_seat_profile", "head_seat",
}}
GUSSET_ROLES = {{
    "horizontal_gusset_profile", "horizontal_gusset_tool", "horizontal_gusset_join",
    "vertical_gusset_profile", "vertical_gusset_tool", "vertical_gusset_join",
}}
BASE_PARAMETER_ROLES = {{
    "parameter_outer_diameter", "parameter_boss_height", "parameter_bore_diameter",
    "parameter_bore_depth", "parameter_head_seat_diameter", "parameter_head_seat_depth",
}}
GUSSET_PARAMETER_ROLES = {{"parameter_rib_thickness", "parameter_rib_length"}}


def _managed(entity):
    attribute = entity.attributes.itemByName(ATTRIBUTE_GROUP, "feature_instance_id")
    return attribute and attribute.value == REQUEST["feature_id"]


def _attribute(entity, name):
    attribute = entity.attributes.itemByName(ATTRIBUTE_GROUP, name)
    return attribute.value if attribute else None


def _resolve_one(design, token):
    entities = design.findEntityByToken(token)
    if len(entities) != 1 or not _managed(entities[0]):
        raise RuntimeError("manual-edit-prevents-update: " + token)
    return entities[0]


def _same_entity(left, right):
    return left == right or getattr(left, "entityToken", None) == getattr(right, "entityToken", None)


def _timeline_group(design):
    groups = design.timeline.timelineGroups
    matches = []
    for index in range(groups.count):
        group = groups.item(index)
        if group.name == REQUEST["timeline_group_name"]:
            matches.append(group)
    if len(matches) != 1:
        raise RuntimeError("manual-edit-prevents-update: timeline group")
    return matches[0]


def _managed_parameters(design):
    parameters = []
    for index in range(design.userParameters.count):
        parameter = design.userParameters.item(index)
        if _managed(parameter):
            parameters.append(parameter)
    return parameters


def _receipt(design):
    entities = [_resolve_one(design, token) for token in REQUEST["object_tokens"]]
    roles = [_attribute(entity, "feature_role") for entity in entities]
    if any(not role for role in roles) or len(set(roles)) != len(roles):
        raise RuntimeError("manual-edit-prevents-update: managed roles")
    role_set = set(roles)
    if role_set not in (BASE_ROLES, BASE_ROLES | GUSSET_ROLES):
        raise RuntimeError("manual-edit-prevents-update: incomplete v1 role shape")
    if any(
        _attribute(entity, "recipe_id") != "boss.heat_set_insert"
        or _attribute(entity, "recipe_version") != "1"
        for entity in entities
    ):
        raise RuntimeError("manual-edit-prevents-update: recipe identity")
    group = _timeline_group(design)
    if group.count != len(entities):
        raise RuntimeError("manual-edit-prevents-update: timeline group membership")
    remaining = list(entities)
    for index in range(group.count):
        member = group.item(index).entity
        for candidate_index, candidate in enumerate(remaining):
            if _same_entity(member, candidate):
                remaining.pop(candidate_index)
                break
        else:
            raise RuntimeError("manual-edit-prevents-update: unmanaged timeline member")
    if remaining:
        raise RuntimeError("manual-edit-prevents-update: missing timeline member")
    parameters = _managed_parameters(design)
    if sorted(parameter.name for parameter in parameters) != sorted(REQUEST["parameter_names"]):
        raise RuntimeError("manual-edit-prevents-update: managed parameters")
    parameter_roles = {{_attribute(parameter, "feature_role") for parameter in parameters}}
    expected_parameter_roles = (
        BASE_PARAMETER_ROLES | GUSSET_PARAMETER_ROLES
        if role_set == BASE_ROLES | GUSSET_ROLES
        else BASE_PARAMETER_ROLES
    )
    if parameter_roles != expected_parameter_roles:
        raise RuntimeError("manual-edit-prevents-update: incomplete v1 parameter shape")
    return entities, parameters, group


def _health_rows(entities):
    rows = []
    for entity in entities:
        state = getattr(entity, "healthState", None)
        rows.append({{
            "role": _attribute(entity, "feature_role"),
            "name": entity.name,
            "token": entity.entityToken,
            "object_type": entity.objectType,
            "health_state": None if state is None else str(state),
            "is_error": state == adsk.fusion.FeatureHealthStates.ErrorFeatureHealthState,
            "message": getattr(entity, "errorOrWarningMessage", "") or "",
        }})
    return rows


def _assert_healthy(entities):
    for entity in entities:
        if getattr(entity, "healthState", None) == adsk.fusion.FeatureHealthStates.ErrorFeatureHealthState:
            raise RuntimeError("timeline-unhealthy: " + (entity.errorOrWarningMessage or entity.name))


def _assert_recipe_dimensions(design, parameters):
    values = {{
        _attribute(parameter, "feature_role").removeprefix("parameter_"):
            design.unitsManager.evaluateExpression(parameter.name, "mm")
        for parameter in parameters
    }}
    if any(value <= 0 for value in values.values()):
        raise RuntimeError("insufficient-wall-thickness: all boss dimensions must be positive")
    if not values["outer_diameter"] > values["head_seat_diameter"] > values["bore_diameter"]:
        raise RuntimeError("insufficient-wall-thickness: outer diameter must exceed head seat and bore diameters")
    if values["bore_depth"] > values["boss_height"]:
        raise RuntimeError("insufficient-wall-thickness: insert bore depth exceeds the boss height")
    if values["head_seat_depth"] >= values["boss_height"]:
        raise RuntimeError("insufficient-wall-thickness: head seat depth must be less than boss height")
    if values["bore_depth"] + values["head_seat_depth"] < values["boss_height"]:
        raise RuntimeError("insufficient-wall-thickness: bore and head seat must form one continuous passage")
    if "rib_length" in values and values["rib_length"] <= values["outer_diameter"] / 2.0:
        raise RuntimeError("insufficient-wall-thickness: gusset length must extend beyond the boss radius")


def _emit(result):
    print(RESULT_BEGIN)
    print(json.dumps(result, sort_keys=True, separators=(",", ":")))
    print(RESULT_END)


def _still_resolves(design, token):
    return bool(design.findEntityByToken(token))


def _group_state(design):
    groups = design.timeline.timelineGroups
    matches = 0
    for index in range(groups.count):
        if groups.item(index).name == REQUEST["timeline_group_name"]:
            matches += 1
    return "deleted" if matches == 0 else "present" if matches == 1 else "ambiguous"


def run(_context: str):
    design = adsk.fusion.Design.cast(adsk.core.Application.get().activeProduct)
    if not design or design.designType != adsk.fusion.DesignTypes.ParametricDesignType:
        raise RuntimeError("invalid-design-type: a parametric design is required")
    document_state = "unchanged"
    details = {{}}
    try:
        entities, parameters, group = _receipt(design)
        if OPERATION == "inspect":
            rows = _health_rows(entities)
            _emit({{
                "ok": not any(row["is_error"] for row in rows),
                "operation": OPERATION,
                "status": "inspected",
                "document_state": document_state,
                "feature_id": REQUEST["feature_id"],
                "parameters": [{{"name": parameter.name, "expression": parameter.expression}} for parameter in parameters],
                "native_objects": rows,
            }})
            return
        if OPERATION == "edit":
            by_name = {{parameter.name: parameter for parameter in parameters}}
            if any(name not in by_name for name in REQUEST["updates"]):
                raise RuntimeError("manual-edit-prevents-update: update parameter")
            _assert_healthy(entities)
            _assert_recipe_dimensions(design, parameters)
            previous = {{parameter.name: parameter.expression for parameter in parameters}}
            original_health = _health_rows(entities)
            try:
                document_state = "dirty"
                for name, expression in REQUEST["updates"].items():
                    by_name[name].expression = expression
                if not design.computeAll():
                    raise RuntimeError("timeline-unhealthy: Compute All failed")
                _assert_recipe_dimensions(design, parameters)
                _assert_healthy(entities)
            except Exception as original:
                rollback_failures = []
                for name, expression in previous.items():
                    try:
                        by_name[name].expression = expression
                    except Exception as error:
                        rollback_failures.append(name + ": " + str(error))
                if not rollback_failures and not design.computeAll():
                    rollback_failures.append("Compute All failed")
                if not rollback_failures and _health_rows(entities) != original_health:
                    rollback_failures.append("managed health did not return to its snapshot")
                if rollback_failures:
                    details["rollback_failures"] = rollback_failures
                    raise RuntimeError("rollback-incomplete: " + "; ".join(rollback_failures)) from original
                document_state = "rolled-back"
                raise
            document_state = "modified"
            _emit({{
                "ok": True,
                "operation": OPERATION,
                "status": "edited",
                "document_state": document_state,
                "feature_id": REQUEST["feature_id"],
                "changed_parameters": sorted(REQUEST["updates"]),
                "native_objects": _health_rows(entities),
            }})
            return

        roles_by_token = {{token: _attribute(entity, "feature_role") for token, entity in zip(REQUEST["object_tokens"], entities)}}
        details["resolved_roles"] = [roles_by_token[token] for token in REQUEST["object_tokens"]]
        document_state = "dirty"
        group_deleted = group.deleteMe(True)
        remaining_tokens = [token for token in REQUEST["object_tokens"] if _still_resolves(design, token)]
        deleted_tokens = [token for token in REQUEST["object_tokens"] if token not in remaining_tokens]
        if not group_deleted or remaining_tokens:
            document_state = "dirty"
            details["remaining_native_roles"] = [roles_by_token[token] for token in remaining_tokens]
            details["deleted_native_roles"] = [roles_by_token[token] for token in deleted_tokens]
            details["timeline_group"] = "deleted" if group_deleted else "partial-or-unknown"
            raise RuntimeError("operation-partial-delete: timeline group deletion incomplete")
        details["deleted_native_roles"] = sorted(roles_by_token.values())
        details["remaining_native_roles"] = []
        details["timeline_group"] = "deleted"
        deleted_parameters = []
        for parameter in reversed(parameters):
            name = parameter.name
            try:
                deleted = parameter.deleteMe()
            except Exception as original:
                raise RuntimeError("operation-partial-delete: " + name + ": " + str(original)) from original
            if not deleted:
                raise RuntimeError("operation-partial-delete: " + name)
            deleted_parameters.append(name)
        document_state = "modified"
        _emit({{
            "ok": True,
            "operation": OPERATION,
            "status": "deleted",
            "document_state": document_state,
            "feature_id": REQUEST["feature_id"],
            "deleted_native_roles": sorted(roles_by_token.values()),
            "deleted_parameter_names": deleted_parameters,
        }})
    except Exception as error:
        if document_state == "dirty":
            remaining_tokens = [token for token in REQUEST["object_tokens"] if _still_resolves(design, token)]
            roles_by_token = details.get("roles_by_token", {{}})
            if not roles_by_token:
                roles_by_token = {{
                    token: role
                    for token, role in zip(REQUEST["object_tokens"], details.get("resolved_roles", []))
                }}
            if roles_by_token:
                details["remaining_native_roles"] = [roles_by_token[token] for token in remaining_tokens]
                details["deleted_native_roles"] = [
                    roles_by_token[token] for token in REQUEST["object_tokens"] if token not in remaining_tokens
                ]
            remaining_parameter_names = sorted(parameter.name for parameter in _managed_parameters(design))
            details["remaining_parameter_names"] = remaining_parameter_names
            details["deleted_parameter_names"] = [
                name for name in REQUEST["parameter_names"] if name not in remaining_parameter_names
            ]
            details["timeline_group"] = _group_state(design)
        details.pop("resolved_roles", None)
        token = str(error).split(":", 1)[0]
        result = {{
            "ok": False,
            "operation": OPERATION,
            "status": "failed-dirty" if document_state == "dirty" else "refused",
            "document_state": document_state,
            "feature_id": REQUEST["feature_id"],
            "failures": [token],
            "error": str(error),
        }}
        result.update(details)
        _emit(result)
        raise
'''
