from __future__ import annotations

import io
import json
import sys
import unittest
from contextlib import redirect_stdout
from types import ModuleType, SimpleNamespace
from unittest.mock import patch

from fusion_design.enclosure_features import (
    BossRequest,
    EntityRef,
    EvidenceClass,
    FeatureParameter,
    RecipeVersion,
    emit_create_boss,
    emit_delete_feature,
    emit_edit_feature,
    emit_inspect_feature,
)


FEATURE_ID = "51be0000-0000-4000-8000-000000000001"
BASE_ROLES = (
    "support_plane",
    "boss_profile",
    "boss_tool",
    "boss_outer",
    "bore_profile",
    "insert_bore",
    "head_seat_profile",
    "head_seat",
)
BASE_TOKENS = tuple(f"{role}-token" for role in BASE_ROLES)
BASE_PARAMETER_NAMES = (
    "fab_pcb_rear_left_boss_outer_diameter",
    "des_pcb_rear_left_boss_height",
    "clr_pcb_rear_left_boss_bore_diameter",
    "clr_pcb_rear_left_boss_bore_depth",
    "clr_pcb_rear_left_boss_head_seat_diameter",
    "clr_pcb_rear_left_boss_head_seat_depth",
)


def parameter(
    semantic_name: str,
    name: str,
    expression: str,
    evidence_class: EvidenceClass,
    *,
    source_ref: str | None = None,
    provisional: bool = False,
    coupon_required: bool = False,
) -> FeatureParameter:
    return FeatureParameter(
        semantic_name=semantic_name,
        name=name,
        expression=expression,
        units="mm",
        evidence_class=evidence_class,
        source_ref=source_ref,
        provisional=provisional,
        coupon_required=coupon_required,
    )


def request() -> BossRequest:
    return BossRequest(
        feature_id=FEATURE_ID,
        instance_name="M3 Insert Boss - PCB Rear Left",
        recipe=RecipeVersion("boss.heat_set_insert", 1),
        parameter_namespace="pcb_rear_left_boss",
        target_body=EntityRef("Root", "adsk::fusion::BRepBody", "target-token"),
        support_face=EntityRef("Root", "adsk::fusion::BRepFace", "face-token"),
        placement=EntityRef("Root", "adsk::fusion::SketchPoint", "point-token"),
        outer_diameter=parameter(
            "outer_diameter",
            "fab_pcb_rear_left_boss_outer_diameter",
            "8 mm",
            EvidenceClass.PROVISIONAL_DEFAULT,
            provisional=True,
        ),
        boss_height=parameter(
            "boss_height",
            "des_pcb_rear_left_boss_height",
            "6 mm",
            EvidenceClass.USER_PREFERENCE,
        ),
        bore_diameter=parameter(
            "bore_diameter",
            "clr_pcb_rear_left_boss_bore_diameter",
            "4 mm",
            EvidenceClass.MANUFACTURER_SPECIFIED,
            source_ref="insert-maker-series-x",
            coupon_required=True,
        ),
        bore_depth=parameter(
            "bore_depth",
            "clr_pcb_rear_left_boss_bore_depth",
            "5 mm",
            EvidenceClass.MANUFACTURER_SPECIFIED,
            source_ref="insert-maker-series-x",
            coupon_required=True,
        ),
        head_seat_diameter=parameter(
            "head_seat_diameter",
            "clr_pcb_rear_left_boss_head_seat_diameter",
            "5.8 mm",
            EvidenceClass.MANUFACTURER_SPECIFIED,
            source_ref="socket-head-maker-series-y",
            coupon_required=True,
        ),
        head_seat_depth=parameter(
            "head_seat_depth",
            "clr_pcb_rear_left_boss_head_seat_depth",
            "3 mm",
            EvidenceClass.MANUFACTURER_SPECIFIED,
            source_ref="socket-head-maker-series-y",
            coupon_required=True,
        ),
        rib_count=4,
        rib_thickness=parameter(
            "rib_thickness",
            "fab_pcb_rear_left_boss_rib_thickness",
            "1.2 mm",
            EvidenceClass.FDM_PROCESS_HEURISTIC,
        ),
        rib_length=parameter(
            "rib_length",
            "des_pcb_rear_left_boss_rib_length",
            "7 mm",
            EvidenceClass.USER_PREFERENCE,
        ),
    )


class EnclosureFeatureTests(unittest.TestCase):
    def test_create_boss_is_deterministic_and_compiles(self) -> None:
        source = emit_create_boss(request())
        self.assertEqual(source, emit_create_boss(request()))
        compile(source, "<enclosure-feature>", "exec")
        self.assertTrue(source.startswith("# Generated by fusion-design enclosure-feature"))
        self.assertIn("participantBodies", source)
        self.assertIn("combineFeatures.createInput(target, tool_bodies)", source)
        self.assertIn("NewBodyFeatureOperation", source)
        self.assertIn("JoinFeatureOperation", source)
        self.assertIn("CutFeatureOperation", source)
        self.assertIn("OffsetStartDefinition.create", source)
        self.assertIn("addCenterPointRectangle", source)
        self.assertIn("constructionPlanes.createInput", source)
        self.assertIn("timelineGroups.add", source)
        self.assertIn("design.computeAll()", source)
        self.assertIn("target.isSolid", source)
        self.assertIn("_cleanup(created)", source)
        self.assertIn("TimelineGroup.cast", source)
        self.assertIn("group.deleteMe(True)", source)
        self.assertIn("bore and head seat must form one continuous passage", source)

    def test_create_boss_source_preserves_policy_boundaries(self) -> None:
        source = emit_create_boss(request())
        for forbidden in (
            "BossFeatures",
            "CustomFeature",
            "executeTextCommand",
            "subprocess",
            "multiprocessing",
            "open(",
            "urllib",
            "requests",
            "fusion-project.json",
            "FUSION_DESIGN_REPORT_BEGIN",
            "nearest",
        ):
            self.assertNotIn(forbidden, source)

    def test_insert_dimensions_require_exact_evidence_and_coupon_status(self) -> None:
        valid = request()
        invalid_bore = parameter(
            "bore_diameter",
            valid.bore_diameter.name,
            "4 mm",
            EvidenceClass.PROVISIONAL_DEFAULT,
            provisional=True,
        )
        with self.assertRaisesRegex(ValueError, "manufacturer-specified or coupon-verified"):
            BossRequest(**{**valid.__dict__, "bore_diameter": invalid_bore})

    def test_parameter_names_and_units_are_explicit(self) -> None:
        valid = request()
        with self.assertRaisesRegex(ValueError, "ownership"):
            BossRequest(
                **{
                    **valid.__dict__,
                    "boss_height": parameter(
                        "boss_height",
                        "pcb_rear_left_boss_height",
                        "6 mm",
                        EvidenceClass.USER_PREFERENCE,
                    ),
                }
            )
        with self.assertRaisesRegex(ValueError, "only mm"):
            BossRequest(
                **{
                    **valid.__dict__,
                    "boss_height": FeatureParameter(
                        "boss_height",
                        valid.boss_height.name,
                        "6 deg",
                        "deg",
                        EvidenceClass.USER_PREFERENCE,
                    ),
                }
            )
        with self.assertRaisesRegex(ValueError, "explicit units"):
            BossRequest(
                **{
                    **valid.__dict__,
                    "boss_height": parameter(
                        "boss_height",
                        valid.boss_height.name,
                        "6",
                        EvidenceClass.USER_PREFERENCE,
                    ),
                }
            )

    def test_lifecycle_emitters_are_explicit_and_compile(self) -> None:
        sources = (
            emit_edit_feature(
                FEATURE_ID,
                {"clr_pcb_rear_left_boss_bore_diameter": "4.1 mm"},
                BASE_PARAMETER_NAMES,
                BASE_TOKENS,
                "M3 Boss - Enclosure Feature",
            ),
            emit_inspect_feature(
                FEATURE_ID,
                BASE_PARAMETER_NAMES,
                BASE_TOKENS,
                "M3 Boss - Enclosure Feature",
            ),
            emit_delete_feature(
                FEATURE_ID,
                BASE_PARAMETER_NAMES,
                BASE_TOKENS,
                "M3 Boss - Enclosure Feature",
            ),
        )
        for source in sources:
            compile(source, "<enclosure-feature-lifecycle>", "exec")
            self.assertIn("manual-edit-prevents-update", source)
            self.assertNotIn("nearest", source)

        edit_source, inspect_source, delete_source = sources
        self.assertIn('"status": "edited"', edit_source)
        self.assertIn("previous = {parameter.name", edit_source)
        self.assertIn("_health_rows", inspect_source)
        self.assertIn("group.deleteMe(True)", delete_source)
        self.assertIn("operation-partial-delete", delete_source)

    def test_edit_expressions_are_validated_before_emission(self) -> None:
        with self.assertRaisesRegex(ValueError, "explicit units"):
            emit_edit_feature(
                FEATURE_ID,
                {"des_pcb_rear_left_boss_height": "7"},
                BASE_PARAMETER_NAMES,
                BASE_TOKENS,
                "M3 Boss - Enclosure Feature",
            )

    def test_lifecycle_rejects_an_incomplete_v1_receipt(self) -> None:
        with self.assertRaisesRegex(ValueError, "complete v1 boss shape"):
            emit_inspect_feature(
                FEATURE_ID,
                BASE_PARAMETER_NAMES[:1],
                BASE_TOKENS[:1],
                "M3 Boss - Enclosure Feature",
            )

    def test_contract_is_closed_over_semantics_units_and_evidence(self) -> None:
        valid = request()
        with self.assertRaisesRegex(ValueError, "exact v1 semantic roles"):
            BossRequest(
                **{
                    **valid.__dict__,
                    "head_seat_depth": parameter(
                        "wrong_role",
                        valid.head_seat_depth.name,
                        "3 mm",
                        EvidenceClass.MANUFACTURER_SPECIFIED,
                        source_ref="socket-head-maker-series-y",
                        coupon_required=True,
                    ),
                }
            )
        with self.assertRaisesRegex(ValueError, "root-component"):
            BossRequest(
                **{
                    **valid.__dict__,
                    "target_body": EntityRef(
                        "Repeated Component",
                        "adsk::fusion::BRepBody",
                        "target-token",
                    ),
                }
            )

    def test_lifecycle_reports_rollback_and_partial_delete_state(self) -> None:
        class Attributes:
            def __init__(self, role: str) -> None:
                self.values = {
                    ("fusion_parametric_design", "feature_instance_id"): FEATURE_ID,
                    ("fusion_parametric_design", "feature_role"): role,
                    ("fusion_parametric_design", "recipe_id"): "boss.heat_set_insert",
                    ("fusion_parametric_design", "recipe_version"): "1",
                }

            def itemByName(self, group: str, name: str):
                value = self.values.get((group, name))
                return None if value is None else SimpleNamespace(value=value)

        class Parameter:
            def __init__(self, name: str, role: str, expression: str) -> None:
                self.name = name
                self.expression = expression
                self.attributes = Attributes(role)
                self.isValid = True

            def deleteMe(self) -> bool:
                self.isValid = False
                return True

        class Entity:
            def __init__(self, role: str, token: str) -> None:
                self.name = role.replace("_", " ").title()
                self.entityToken = token
                self.objectType = "adsk::fusion::CombineFeature"
                self.attributes = Attributes(role)
                self.healthState = "healthy"
                self.errorOrWarningMessage = ""
                self.isValid = True

        class Group:
            name = "M3 Boss - Enclosure Feature"

            def __init__(
                self,
                entities: list[Entity],
                partial_delete: bool,
                raise_after_delete: bool,
            ) -> None:
                self.entities = entities
                self.partial_delete = partial_delete
                self.raise_after_delete = raise_after_delete
                self.count = len(entities)

            def item(self, index: int):
                return SimpleNamespace(entity=self.entities[index])

            def deleteMe(self, _delete_contents: bool) -> bool:
                if self.raise_after_delete:
                    self.entities[0].isValid = False
                    raise RuntimeError("injected delete failure")
                if self.partial_delete:
                    self.entities[0].isValid = False
                    return False
                for entity in self.entities:
                    entity.isValid = False
                return True

        class Design:
            designType = "parametric"

            def __init__(
                self,
                partial_delete: bool = False,
                raise_after_delete: bool = False,
                fail_health: bool = True,
            ) -> None:
                self.entities = [Entity(role, token) for role, token in zip(BASE_ROLES, BASE_TOKENS)]
                parameter_roles = (
                    "parameter_outer_diameter",
                    "parameter_boss_height",
                    "parameter_bore_diameter",
                    "parameter_bore_depth",
                    "parameter_head_seat_diameter",
                    "parameter_head_seat_depth",
                )
                expressions = ("8 mm", "6 mm", "4 mm", "5 mm", "5.8 mm", "3 mm")
                self.parameters = [
                    Parameter(name, role, expression)
                    for name, role, expression in zip(
                        BASE_PARAMETER_NAMES, parameter_roles, expressions
                    )
                ]
                self.group = Group(self.entities, partial_delete, raise_after_delete)
                self.timeline = SimpleNamespace(
                    timelineGroups=SimpleNamespace(count=1, item=lambda _index: self.group)
                )
                self.userParameters = SimpleNamespace(
                    count=len(self.parameters),
                    item=lambda index: self.parameters[index],
                    itemByName=lambda name: next(
                        (parameter for parameter in self.parameters if parameter.name == name and parameter.isValid),
                        None,
                    ),
                )
                self.compute_calls = 0
                self.fail_health = fail_health
                self.unitsManager = SimpleNamespace(
                    evaluateExpression=lambda name, _units: float(
                        self.userParameters.itemByName(name).expression.split()[0]
                    )
                )

            def findEntityByToken(self, token: str):
                return [
                    entity
                    for entity in self.entities
                    if token == entity.entityToken and entity.isValid
                ]

            def computeAll(self) -> bool:
                self.compute_calls += 1
                if self.fail_health and self.compute_calls == 1:
                    self.entities[3].healthState = "error"
                    self.entities[3].errorOrWarningMessage = "injected health failure"
                else:
                    self.entities[3].healthState = "healthy"
                    self.entities[3].errorOrWarningMessage = ""
                return True

        def execute(source: str, design: Design) -> tuple[dict[str, object], RuntimeError]:
            adsk = ModuleType("adsk")
            core = ModuleType("adsk.core")
            fusion = ModuleType("adsk.fusion")
            adsk.core = core
            adsk.fusion = fusion
            core.Application = SimpleNamespace(
                get=lambda: SimpleNamespace(activeProduct=design)
            )
            fusion.Design = SimpleNamespace(cast=lambda product: product)
            fusion.DesignTypes = SimpleNamespace(ParametricDesignType="parametric")
            fusion.FeatureHealthStates = SimpleNamespace(ErrorFeatureHealthState="error")
            namespace: dict[str, object] = {}
            output = io.StringIO()
            with patch.dict(sys.modules, {"adsk": adsk, "adsk.core": core, "adsk.fusion": fusion}):
                exec(source, namespace)
                with self.assertRaises(RuntimeError) as caught, redirect_stdout(output):
                    namespace["run"]("")
            lines = output.getvalue().splitlines()
            return json.loads(lines[lines.index("FUSION_ENCLOSURE_FEATURE_RESULT_BEGIN") + 1]), caught.exception

        edit_design = Design()
        edit_source = emit_edit_feature(
            FEATURE_ID,
            {"des_pcb_rear_left_boss_height": "7 mm"},
            BASE_PARAMETER_NAMES,
            BASE_TOKENS,
            "M3 Boss - Enclosure Feature",
        )
        edit_result, edit_error = execute(edit_source, edit_design)
        self.assertIn("timeline-unhealthy", str(edit_error))
        self.assertEqual(
            "6 mm",
            edit_design.userParameters.itemByName("des_pcb_rear_left_boss_height").expression,
        )
        self.assertEqual("rolled-back", edit_result["document_state"])
        self.assertEqual("refused", edit_result["status"])

        invariant_design = Design(fail_health=False)
        invariant_source = emit_edit_feature(
            FEATURE_ID,
            {"fab_pcb_rear_left_boss_outer_diameter": "5 mm"},
            BASE_PARAMETER_NAMES,
            BASE_TOKENS,
            "M3 Boss - Enclosure Feature",
        )
        invariant_result, invariant_error = execute(invariant_source, invariant_design)
        self.assertIn("insufficient-wall-thickness", str(invariant_error))
        self.assertEqual(
            "8 mm",
            invariant_design.userParameters.itemByName(
                "fab_pcb_rear_left_boss_outer_diameter"
            ).expression,
        )
        self.assertEqual("rolled-back", invariant_result["document_state"])
        self.assertEqual("refused", invariant_result["status"])

        delete_design = Design(partial_delete=True)
        delete_source = emit_delete_feature(
            FEATURE_ID,
            BASE_PARAMETER_NAMES,
            BASE_TOKENS,
            "M3 Boss - Enclosure Feature",
        )
        delete_result, delete_error = execute(delete_source, delete_design)
        self.assertIn("operation-partial-delete", str(delete_error))
        self.assertEqual("dirty", delete_result["document_state"])
        self.assertEqual("failed-dirty", delete_result["status"])
        self.assertEqual(["support_plane"], delete_result["deleted_native_roles"])

        raised_delete_design = Design(raise_after_delete=True)
        raised_result, raised_error = execute(delete_source, raised_delete_design)
        self.assertIn("injected delete failure", str(raised_error))
        self.assertEqual("dirty", raised_result["document_state"])
        self.assertEqual("failed-dirty", raised_result["status"])
        self.assertEqual(["support_plane"], raised_result["deleted_native_roles"])


if __name__ == "__main__":
    unittest.main()
