"""Tests for the pure-Python .bgcode container reader (plan unit U1).

Every container here is hand-built from the format definition, so the tests
pin the byte layout rather than whatever a particular writer emits.
"""

from __future__ import annotations

import gzip
from pathlib import Path
import struct
import tempfile
import unittest
import zlib

from fusion_design.prusaslicer_bgcode import BgcodeError, read_bgcode


GCODE = (
    "; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 04:32:04 UTC\n"
    "; filament used [g] = 3.93\n"
    "; total filament used [g] = 3.93\n"
)

_HEADER = struct.Struct("<IIH")


def _block(block_type: int, compression: int, payload: bytes, raw_size: int | None = None) -> bytes:
    flags = block_type | (compression << 5)
    return _HEADER.pack(len(payload), len(payload) if raw_size is None else raw_size, flags) + payload


def _container(*blocks: bytes) -> bytes:
    return b"GCDE\x01" + b"".join(blocks)


def _heatshrink_literals(data: bytes, window_sz2: int = 9, lookahead_sz2: int = 4) -> bytes:
    """Encode data as all-literal heatshrink tokens (tag 0, then the byte)."""
    bits = "".join("0" + format(byte, "08b") for byte in data)
    bits += "0" * (-len(bits) % 8)  # the writer zero-pads the final byte
    return bytes([(window_sz2 << 4) | lookahead_sz2]) + int(bits, 2).to_bytes(len(bits) // 8, "big")


def _heatshrink_backref(index: int, count: int, window_sz2: int = 9, lookahead_sz2: int = 4) -> bytes:
    """A single back-reference token: tag 1, index, count - 1, zero-padded."""
    bits = "1" + format(index, f"0{window_sz2}b") + format(count - 1, f"0{lookahead_sz2}b")
    bits += "0" * (-len(bits) % 8)
    return bytes([(window_sz2 << 4) | lookahead_sz2]) + int(bits, 2).to_bytes(len(bits) // 8, "big")


class GzipContainerTests(unittest.TestCase):
    def test_gzip_block_round_trips_the_gcode_text(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(_container(_block(0, 1, gzip.compress(GCODE.encode()), raw_size=len(GCODE))))
            self.assertEqual(GCODE, read_bgcode(path))

    def test_zlib_wrapped_deflate_is_accepted_too(self) -> None:
        payload = zlib.compress(GCODE.encode())
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(_container(_block(0, 1, payload, raw_size=len(GCODE))))
            self.assertEqual(GCODE, read_bgcode(path))

    def test_uncompressed_gcode_block_is_read_verbatim(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(_container(_block(0, 0, GCODE.encode())))
            self.assertEqual(GCODE, read_bgcode(path))


class HeatshrinkContainerTests(unittest.TestCase):
    def test_header_declared_window_and_lookahead_are_honored(self) -> None:
        # Small non-default parameters: the decoder must read them from the
        # header, not assume the encoder defaults.
        payload = _heatshrink_literals(GCODE.encode(), window_sz2=5, lookahead_sz2=3)
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(_container(_block(0, 2, payload, raw_size=len(GCODE))))
            self.assertEqual(GCODE, read_bgcode(path))

    def test_back_reference_repeats_the_window(self) -> None:
        # One continuous token stream: "abc" as literals, then a single back
        # reference (index 2, count 6), which repeats the whole 3-byte window
        # twice -- overlapping copies are legal.
        bits = "".join("0" + format(byte, "08b") for byte in b"abc")
        bits += "1" + format(2, "09b") + format(5, "04b")
        bits += "0" * (-len(bits) % 8)
        payload = bytes([0x94]) + int(bits, 2).to_bytes(len(bits) // 8, "big")
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(_container(_block(0, 2, payload, raw_size=9)))
            self.assertEqual("abcabcabc", read_bgcode(path))

    def test_a_back_reference_past_the_start_of_output_is_corruption(self) -> None:
        payload = _heatshrink_backref(index=5, count=1)
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(_container(_block(0, 2, payload, raw_size=1)))
            with self.assertRaisesRegex(BgcodeError, "back reference"):
                read_bgcode(path)


class ContainerStructureTests(unittest.TestCase):
    def test_gcode_blocks_are_joined_in_order_across_mixed_blocks(self) -> None:
        container = _container(
            _block(5, 0, b"file metadata"),          # file metadata: skipped
            _block(0, 1, gzip.compress(b"part one\n"), raw_size=9),
            _block(99, 0, b"unknown block type"),    # unknown: skipped
            _block(0, 2, _heatshrink_literals(b"part two\n"), raw_size=9),
            _block(8, 0, b"thumbnail"),              # thumbnail: skipped
        )
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(container)
            self.assertEqual("part one\npart two\n", read_bgcode(path))

    def test_wrong_magic_is_a_named_failure(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(b"NOPE\x01")
            with self.assertRaisesRegex(BgcodeError, "magic"):
                read_bgcode(path)

    def test_unsupported_version_is_a_named_failure(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(b"GCDE\x02")
            with self.assertRaisesRegex(BgcodeError, "version"):
                read_bgcode(path)

    def test_truncated_file_header_is_a_named_failure(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(b"GC")
            with self.assertRaisesRegex(BgcodeError, "Truncated"):
                read_bgcode(path)

    def test_truncated_block_header_is_a_named_failure(self) -> None:
        # A valid container followed by four dangling bytes: the reader starts
        # a next block header it can never finish.
        container = _container(_block(0, 0, GCODE.encode())) + b"\x00\x00\x00\x01"
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(container)
            with self.assertRaisesRegex(BgcodeError, "block header"):
                read_bgcode(path)

    def test_truncated_block_payload_is_a_named_failure(self) -> None:
        container = _container(_block(0, 0, GCODE.encode()))[:-10]
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(container)
            with self.assertRaisesRegex(BgcodeError, "payload"):
                read_bgcode(path)

    def test_declared_size_mismatch_is_a_named_failure(self) -> None:
        # Header claims 100 uncompressed bytes; the gzip block decodes to fewer.
        container = _container(_block(0, 1, gzip.compress(GCODE.encode()), raw_size=100))
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(container)
            with self.assertRaisesRegex(BgcodeError, "declares 100"):
                read_bgcode(path)

    def test_corrupt_gzip_payload_is_a_named_failure(self) -> None:
        container = _container(_block(0, 1, b"\x1f\x8b not really gzip"))
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(container)
            with self.assertRaisesRegex(BgcodeError, "gzip/deflate"):
                read_bgcode(path)

    def test_unknown_compression_is_a_named_failure(self) -> None:
        container = _container(_block(0, 7, b"mystery"))
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(container)
            with self.assertRaisesRegex(BgcodeError, "compression 7"):
                read_bgcode(path)

    def test_container_without_gcode_blocks_is_a_named_failure(self) -> None:
        container = _container(_block(5, 0, b"metadata only"))
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.bgcode"
            path.write_bytes(container)
            with self.assertRaisesRegex(BgcodeError, "no G-code block"):
                read_bgcode(path)


if __name__ == "__main__":
    unittest.main()
