from __future__ import annotations

import hashlib
from pathlib import Path
import stat
import subprocess
import tempfile
import unittest
from unittest import mock

from fusion_design import prusaslicer_slice
from fusion_design.prusaslicer_project import ResolvedPresets
from fusion_design.prusaslicer_slice import (
    IncompleteProfileSetError,
    parse_gcode_statistics,
    require_complete_profile_set,
    resolve_executable,
    slice_project,
)


# Captured verbatim from a real PrusaSlicer 2.9.6 run on this host
# (Original Prusa XL, --binary-gcode=0). The five columns are the five tools.
GCODE = """; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 04:32:04 UTC

G1 X10 Y10 E1
; filament used [mm] = 1284.99, 0.00, 0.00, 0.00, 0.00
; filament used [cm3] = 3.09, 0.00, 0.00, 0.00, 0.00
; filament used [g] = 3.93, 0.00, 0.00, 0.00, 0.00
; total filament used [g] = 3.93
; total filament cost = 0.12
; estimated printing time (normal mode) = 18m 4s
; estimated printing time (silent mode) = 18m 46s
"""

PRESETS = ResolvedPresets(
    printer="Original Prusa XL - 5T Input Shaper HF0.4 & HF0.6 nozzles",
    filament="Prusament PETG @XL HF0.4",
    print_settings="0.20mm SPEED @XLIS HF0.4",
    config_root="/config/root",
)


class _Runner:
    """Records every command it is asked to run; never starts a process."""

    def __init__(self, returncode: int = 0, stdout: str = "", stderr: str = "", gcode: str | None = GCODE):
        self.calls: list[list[str]] = []
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr
        self.gcode = gcode

    def __call__(self, command, **kwargs):
        self.calls.append(list(command))
        if self.gcode is not None and "--output" in command:
            Path(command[command.index("--output") + 1]).write_text(self.gcode, encoding="utf-8")
        return subprocess.CompletedProcess(command, self.returncode, self.stdout, self.stderr)


def _fake_slicer(root: Path, exit_code: int = 0) -> Path:
    """A stand-in binary that emits canned G-code. The real slicer is never run in tests."""
    script = root / f"fake-slicer-{exit_code}"
    script.write_text(
        "#!/usr/bin/env python3\n"
        "import sys\n"
        "argv = sys.argv[1:]\n"
        "if '--output' in argv:\n"
        "    open(argv[argv.index('--output') + 1], 'w').write('''" + GCODE + "''')\n"
        f"sys.exit({exit_code})\n",
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IXUSR)
    return script


def _project(root: Path) -> Path:
    path = root / "project.3mf"
    path.write_bytes(b"PK\x03\x04 pretend project")
    return path


def _bindings(project: Path, **extra) -> dict:
    """The chain a real caller passes: the project hash plus what produced it."""
    return {
        "project_sha256": hashlib.sha256(project.read_bytes()).hexdigest(),
        "manifest_sha256": "b" * 64,
        "export_index_sha256": "c" * 64,
        "verification_report_sha256": "d" * 64,
        "export_run_id": "0123456789abcdef0123456789abcdef",
        **extra,
    }


class IncompleteProfileSetTests(unittest.TestCase):
    """The actual defect: a partial profile set is what segfaults PrusaSlicer."""

    def test_each_missing_kind_is_refused_by_name(self) -> None:
        complete = {"printer": "P", "print": "Q", "filament": "M"}
        for kind in ("printer", "print", "filament"):
            for empty in (None, "", "   "):
                with self.subTest(kind=kind, empty=empty):
                    partial = {**complete, kind: empty}
                    with self.assertRaises(IncompleteProfileSetError) as caught:
                        require_complete_profile_set(partial)
                    self.assertIn(kind, str(caught.exception))
                    self.assertIn("139", str(caught.exception))

    def test_complete_set_is_returned_stripped(self) -> None:
        self.assertEqual(
            {"printer": "P", "print": "Q", "filament": "M"},
            require_complete_profile_set({"printer": " P ", "print": "Q", "filament": "M"}),
        )

    def test_resolved_presets_are_accepted(self) -> None:
        self.assertEqual(
            {
                "printer": PRESETS.printer,
                "print": PRESETS.print_settings,
                "filament": PRESETS.filament,
            },
            require_complete_profile_set(PRESETS),
        )

    def test_nothing_is_executed_when_the_set_is_incomplete(self) -> None:
        runner = _Runner()
        with tempfile.TemporaryDirectory() as temporary:
            project = _project(Path(temporary))
            with self.assertRaises(IncompleteProfileSetError):
                slice_project(
                    project,
                    {"printer": "P", "print": "Q"},
                    bindings=_bindings(project),
                    executable=project,  # any existing file; must never be reached
                    runner=runner,
                )
        self.assertEqual([], runner.calls)


class ExecutableDiscoveryTests(unittest.TestCase):
    def test_explicit_path_wins_and_a_missing_one_is_not_substituted(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            binary = Path(temporary) / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            self.assertEqual(binary, resolve_executable(binary))
            self.assertIsNone(resolve_executable(Path(temporary) / "absent"))

    def test_bundle_then_path_then_none(self) -> None:
        with mock.patch.object(prusaslicer_slice, "BUNDLE_EXECUTABLE") as bundle:
            bundle.is_file.return_value = True
            self.assertIs(bundle, resolve_executable())
            bundle.is_file.return_value = False
            with mock.patch.object(prusaslicer_slice.shutil, "which", return_value="/usr/bin/prusa-slicer"):
                self.assertEqual(Path("/usr/bin/prusa-slicer"), resolve_executable())
            with mock.patch.object(prusaslicer_slice.shutil, "which", return_value=None):
                self.assertIsNone(resolve_executable())

    def test_unavailable_slicer_is_a_structured_result_not_a_crash(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project = _project(Path(temporary))
            with mock.patch.object(prusaslicer_slice, "resolve_executable", return_value=None):
                result = slice_project(project, PRESETS, bindings=_bindings(project), runner=_Runner())
        self.assertTrue(result["supported"])
        self.assertFalse(result["attempted"])
        self.assertFalse(result["ok"])
        self.assertIn("No PrusaSlicer executable was found", result["reason"])


class StatisticsParsingTests(unittest.TestCase):
    def test_real_footer_is_parsed(self) -> None:
        statistics, absent = parse_gcode_statistics(GCODE)
        self.assertEqual([], absent)
        self.assertEqual("18m 4s", statistics["estimated_printing_time_normal"])
        self.assertEqual("18m 46s", statistics["estimated_printing_time_silent"])
        self.assertEqual([1284.99, 0.0, 0.0, 0.0, 0.0], statistics["filament_used_mm"])
        self.assertEqual(1284.99, statistics["filament_used_mm_total"])
        self.assertEqual(3.93, statistics["filament_used_g_total"])
        self.assertEqual(3.93, statistics["total_filament_used_g"])
        self.assertEqual(3.09, statistics["filament_used_cm3_total"])

    def test_absent_and_unparseable_fields_are_reported_not_guessed(self) -> None:
        statistics, absent = parse_gcode_statistics(
            "; filament used [g] = n/a\n; estimated printing time (normal mode) = 1h 2m\n"
        )
        self.assertEqual({"estimated_printing_time_normal": "1h 2m"}, statistics)
        self.assertIn("filament_used_g", absent)
        self.assertIn("filament_used_mm", absent)
        self.assertIn("total_filament_used_g", absent)

    def test_binary_gcode_yields_no_invented_numbers(self) -> None:
        statistics, absent = parse_gcode_statistics("GCDE\x00\x01Producer=PrusaSlicer 2.9.6")
        self.assertEqual({}, statistics)
        self.assertEqual(len(prusaslicer_slice._STATISTIC_KEYS), len(absent))


class SliceInvocationTests(unittest.TestCase):
    def test_only_the_resolved_binary_is_invoked_with_the_whole_profile_set(self) -> None:
        runner = _Runner()
        with tempfile.TemporaryDirectory() as temporary:
            project = _project(Path(temporary))
            binary = Path(temporary) / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            slice_project(project, PRESETS, bindings=_bindings(project), executable=binary, runner=runner)

        self.assertEqual(1, len(runner.calls))
        command = runner.calls[0]
        self.assertEqual(str(binary), command[0])
        for flag, value in (
            ("--printer-profile", PRESETS.printer),
            ("--print-profile", PRESETS.print_settings),
            ("--material-profile", PRESETS.filament),
        ):
            self.assertIn(flag, command)
            self.assertEqual(value, command[command.index(flag) + 1])
        # Presets were resolved against this root, so slicing uses the same one.
        self.assertEqual(PRESETS.config_root, command[command.index("--datadir") + 1])
        self.assertIn("--binary-gcode=0", command)
        self.assertTrue(all(isinstance(argument, str) for argument in command))

    def test_success_binds_statistics_to_project_and_gcode_evidence(self) -> None:
        runner = _Runner(stdout="Slicing result exported to project.gcode\n")
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, bindings=_bindings(project), executable=binary, runner=runner)

            self.assertTrue(result["ok"])
            self.assertEqual(0, result["exit_code"])
            self.assertEqual(hashlib.sha256(project.read_bytes()).hexdigest(), result["project_sha256"])
            gcode = Path(result["gcode_path"])
            self.assertEqual(hashlib.sha256(gcode.read_bytes()).hexdigest(), result["gcode_sha256"])
            self.assertEqual(gcode.stat().st_size, result["gcode_byte_size"])
        self.assertEqual("PrusaSlicer 2.9.6", result["slicer_version"])
        self.assertEqual(str(binary), result["executable"])
        self.assertEqual(
            {"printer": PRESETS.printer, "print": PRESETS.print_settings, "filament": PRESETS.filament},
            result["presets"],
        )
        self.assertEqual("18m 4s", result["statistics"]["estimated_printing_time_normal"])
        self.assertEqual([], result["warnings"])

    def test_segfault_exit_is_a_structured_failure_with_diagnostics(self) -> None:
        runner = _Runner(returncode=139, stderr="boom\n", gcode=None)
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, bindings=_bindings(project), executable=binary, runner=runner)
            self.assertFalse((root / "project.gcode").exists())

        self.assertFalse(result["ok"])
        self.assertTrue(result["attempted"])
        self.assertEqual(139, result["exit_code"])
        self.assertIn("SIGSEGV", result["failure"])
        self.assertEqual("boom", result["stderr_tail"])
        self.assertNotIn("statistics", result)

    def test_exit_zero_without_gcode_is_still_a_failure(self) -> None:
        runner = _Runner(gcode=None, stderr="nothing written")
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, bindings=_bindings(project), executable=binary, runner=runner)
        self.assertFalse(result["ok"])
        self.assertIn("wrote no G-code", result["failure"])
        self.assertNotIn("statistics", result)

    def test_timeout_is_reported_and_cannot_hang(self) -> None:
        def timing_out(command, **kwargs):
            self.assertEqual(7, kwargs["timeout"])
            raise subprocess.TimeoutExpired(command, kwargs["timeout"])

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, bindings=_bindings(project), executable=binary, timeout=7, runner=timing_out)

        self.assertFalse(result["ok"])
        self.assertIsNone(result["exit_code"])
        self.assertIn("did not finish within 7 seconds", result["failure"])
        self.assertNotIn("statistics", result)

    def test_warnings_are_collected_from_slicer_output(self) -> None:
        runner = _Runner(stderr="WARNING: object is too tall\nfine\n")
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, bindings=_bindings(project), executable=binary, runner=runner)
        self.assertEqual(["WARNING: object is too tall"], result["warnings"])

    def test_existing_gcode_is_never_overwritten(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            (root / "project.gcode").write_text("earlier", encoding="utf-8")
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "Refusing to overwrite"):
                slice_project(project, PRESETS, bindings=_bindings(project), executable=binary, runner=_Runner())
            self.assertEqual("earlier", (root / "project.gcode").read_text(encoding="utf-8"))


class WindowTrimmingTests(unittest.TestCase):
    """Direct cover for the two helpers the parsing correctness rests on."""

    def test_partial_lines_at_a_window_boundary_are_discarded(self) -> None:
        window = b"used [g] = 41.9\n; next = 1\n; trailing partial = 4"
        self.assertEqual(
            b"; next = 1\n; trailing partial = 4",
            prusaslicer_slice._whole_lines(window, drop_leading=True, drop_trailing=False),
        )
        self.assertEqual(
            b"used [g] = 41.9\n; next = 1\n",
            prusaslicer_slice._whole_lines(window, drop_leading=False, drop_trailing=True),
        )
        # A window holding no complete line yields nothing rather than a fragment.
        self.assertEqual(
            b"", prusaslicer_slice._whole_lines(b"g] = 41.9", drop_leading=True, drop_trailing=False)
        )
        self.assertEqual(
            b"", prusaslicer_slice._whole_lines(b"g] = 41.9", drop_leading=False, drop_trailing=True)
        )
        self.assertEqual(
            window, prusaslicer_slice._whole_lines(window, drop_leading=False, drop_trailing=False)
        )

    def test_the_summary_block_is_the_trailing_comment_run_only(self) -> None:
        self.assertEqual(
            ["; a = 1", "; b = 2"],
            prusaslicer_slice.summary_block("; spoof = 9\nG1 X1\n; a = 1\n; b = 2\n"),
        )
        # Stops at the config marker, and at the last non-comment line before it.
        self.assertEqual(
            ["; a = 1"],
            prusaslicer_slice.summary_block(
                "; a = 1\n; prusaslicer_config = begin\n; a = 9\n; prusaslicer_config = end\n"
            ),
        )
        self.assertEqual([], prusaslicer_slice.summary_block("; spoof = 9\nG1 X1\nM84\n"))
        self.assertEqual([], prusaslicer_slice.summary_block(""))


class SliceBindingTests(unittest.TestCase):
    """Statistics have to attach to the project the caller says they came from."""

    def test_project_replaced_after_the_binding_is_refused(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            bindings = _bindings(project)
            project.write_bytes(b"PK\x03\x04 a different project entirely")
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            runner = _Runner()
            with self.assertRaisesRegex(ValueError, "changed between building the project and slicing"):
                slice_project(project, PRESETS, bindings=bindings, executable=binary, runner=runner)
            self.assertEqual([], runner.calls)

    def test_a_missing_or_malformed_project_hash_is_refused(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            for bindings in ({}, {"project_sha256": None}, {"project_sha256": "nope"}):
                with self.subTest(bindings=bindings):
                    with self.assertRaisesRegex(ValueError, "lowercase hex SHA-256"):
                        slice_project(project, PRESETS, bindings=bindings, runner=_Runner())

    def test_a_plain_dict_without_a_datadir_is_refused(self) -> None:
        # Measured against PrusaSlicer 2.9.6: an unresolvable-but-complete set
        # exits 1 rather than segfaulting, so this is not a crash guard -- it stops
        # names validated against one configuration being resolved in another.
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            runner = _Runner()
            with self.assertRaisesRegex(ValueError, "datadir is required"):
                slice_project(
                    project,
                    {"printer": "P", "print": "Q", "filament": "M"},
                    bindings=_bindings(project),
                    runner=runner,
                )
            self.assertEqual([], runner.calls)

    def test_the_whole_chain_is_echoed_into_the_result(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            bindings = _bindings(project)
            result = slice_project(
                project, PRESETS, bindings=bindings, executable=binary, runner=_Runner()
            )
        self.assertEqual(bindings, result["bindings"])
        self.assertEqual(bindings["project_sha256"], result["project_sha256"])
        for key in ("manifest_sha256", "export_index_sha256", "verification_report_sha256", "export_run_id"):
            self.assertIn(key, result["bindings"])


class GcodeWindowTests(unittest.TestCase):
    """A number recovered from a truncated read is inferred, not measured."""

    FOOTER = (
        "; filament used [mm] = 1284.99\n"
        "; filament used [cm3] = 3.09\n"
        "; filament used [g] = 41.9\n"
        "; total filament used [g] = 41.9\n"
        "; estimated printing time (normal mode) = 18m 4s\n"
        "; estimated printing time (silent mode) = 18m 46s\n"
    )

    def _slice(self, root: Path, gcode: str) -> dict:
        project = _project(root)
        binary = root / "PrusaSlicer"
        binary.write_text("", encoding="utf-8")
        return slice_project(
            project,
            PRESETS,
            bindings=_bindings(project),
            executable=binary,
            runner=_Runner(gcode=gcode),
        )

    def test_a_statistic_straddling_the_head_boundary_is_never_half_read(self) -> None:
        # The head window used to be joined to the tail with a newline, which
        # completed its truncated last line: a real 41.9 g was reported as 4.0 g.
        gcode = (
            "; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 04:32:04 UTC\n"
            + "; comment padding\n" * 400
            + "; total filament used [g] = 41.9\n"
            + "G1 X10 Y10 E1\n" * 200000
            + self.FOOTER
        )
        self.assertGreater(len(gcode.encode("utf-8")), prusaslicer_slice._HEAD_BYTES)
        with tempfile.TemporaryDirectory() as temporary:
            result = self._slice(Path(temporary), gcode)
        self.assertTrue(result["ok"], result)
        self.assertEqual(41.9, result["statistics"]["total_filament_used_g"])

    # Deliberately a few hundred bytes: small parts routinely slice under the tail
    # window, and that is exactly the case where selecting the tail excludes
    # nothing at all. The start G-code must be excluded by its *position*, not by
    # being lucky enough to fall outside a window.
    START_GCODE_SPOOF = (
        "; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 04:32:04 UTC\n"
        "; total filament used [g] = 0.1\n"
        "; estimated printing time (normal mode) = 0h 1m\n"
        "M104 S215\n"
        "G28\n"
        "G1 X10 Y10 E1\n"
        "M84\n"
    )

    def test_start_gcode_alone_yields_no_statistics_in_a_small_file(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            result = self._slice(Path(temporary), self.START_GCODE_SPOOF)
        self.assertLess(len(self.START_GCODE_SPOOF.encode("utf-8")), prusaslicer_slice._TAIL_BYTES)
        self.assertTrue(result["gcode_window"]["whole_file_read"])
        self.assertFalse(result["ok"])
        self.assertEqual({}, result["statistics"])
        self.assertIn("no statistic was readable", result["failure"])

    def test_start_gcode_never_outvotes_the_real_footer_in_a_small_file(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            result = self._slice(Path(temporary), self.START_GCODE_SPOOF + self.FOOTER)
        self.assertTrue(result["ok"], result)
        self.assertTrue(result["gcode_window"]["whole_file_read"])
        self.assertEqual(41.9, result["statistics"]["total_filament_used_g"])
        self.assertEqual("18m 4s", result["statistics"]["estimated_printing_time_normal"])

    def test_the_config_dump_is_not_mistaken_for_the_summary(self) -> None:
        # The dump is itself a run of "; key = value" lines and sits after the
        # summary, so the scan has to stop at its marker rather than at EOF.
        gcode = (
            self.START_GCODE_SPOOF
            + self.FOOTER
            + "; prusaslicer_config = begin\n"
            + "; total filament used [g] = 999.0\n"
            + "; prusaslicer_config = end\n"
        )
        with tempfile.TemporaryDirectory() as temporary:
            result = self._slice(Path(temporary), gcode)
        self.assertTrue(result["ok"], result)
        self.assertEqual(41.9, result["statistics"]["total_filament_used_g"])

    def test_statistics_outside_the_window_are_a_failure_not_an_empty_block(self) -> None:
        gcode = (
            "; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 04:32:04 UTC\n"
            + self.FOOTER
            + "; prusaslicer_config = begin\n"
            + "; padding_key = padding_value\n" * 60000
            + "; prusaslicer_config = end\n"
        )
        self.assertGreater(len(gcode.encode("utf-8")), prusaslicer_slice._TAIL_BYTES)
        with tempfile.TemporaryDirectory() as temporary:
            result = self._slice(Path(temporary), gcode)
        self.assertFalse(result["ok"])
        self.assertIn("no statistic was readable", result["failure"])
        self.assertFalse(result["gcode_window"]["whole_file_read"])

    def test_a_small_gcode_reports_the_window_as_complete(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            result = self._slice(Path(temporary), GCODE)
        self.assertTrue(result["ok"])
        self.assertTrue(result["gcode_window"]["whole_file_read"])


class RealSubprocessTests(unittest.TestCase):
    """Exercises the actual subprocess path against a stand-in, never real PrusaSlicer."""

    def test_real_run_parses_statistics(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            result = slice_project(
                project, PRESETS, bindings=_bindings(project), executable=_fake_slicer(root), datadir=root
            )
        self.assertTrue(result.get("ok"), result)
        self.assertEqual(3.93, result["statistics"]["total_filament_used_g"])
        self.assertEqual("PrusaSlicer 2.9.6", result["slicer_version"])

    def test_real_non_zero_exit_fails_closed(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            result = slice_project(
                project,
                PRESETS,
                bindings=_bindings(project),
                executable=_fake_slicer(root, exit_code=139),
                datadir=root,
            )
        self.assertFalse(result["ok"])
        self.assertEqual(139, result["exit_code"])
        self.assertIn("SIGSEGV", result["failure"])


class ExecutionIsConfinedTests(unittest.TestCase):
    """Slicing needs subprocess, so the no-execution guarantee moved rather than vanished."""

    def test_prusaslicer_slice_is_the_only_module_that_can_start_a_process(self) -> None:
        from test_prusaslicer_project import process_execution_offenses

        package = Path(prusaslicer_slice.__file__).parent
        offenders = {
            module.name
            for module in sorted(package.glob("*.py"))
            if process_execution_offenses(module.read_text(encoding="utf-8"))
        }
        self.assertEqual({"prusaslicer_slice.py"}, offenders)

    def test_the_command_is_an_argument_list_and_never_a_shell_string(self) -> None:
        source = Path(prusaslicer_slice.__file__).read_text(encoding="utf-8")
        self.assertNotIn("shell=True", source)
        self.assertNotIn("subprocess.Popen", source)
        self.assertNotIn("os.system", source)


if __name__ == "__main__":
    unittest.main()
