"""Tests for the slice-in-the-loop optimizer (U5), fake-runner based."""

from __future__ import annotations

from pathlib import Path
import subprocess
import tempfile

import unittest
from unittest import mock
import json
from fusion_design import prusaslicer_optimize
from test_prusaslicer_project import _Fixture, _config_root, _presets, _intent


GCODE = """; generated by PrusaSlicer 2.9.6 on 2026-08-21

; filament used [g] = 3.93
; total filament used [g] = 3.93
; estimated printing time (normal mode) = 18m 4s
; estimated printing time (silent mode) = 18m 46s
"""


class FakeRunner:
    """Records slice commands; writes G-code whose timing is injected per call."""

    def __init__(self, durations: list[str]):
        # One "18m 4s"-style duration per expected slice call, in call order.
        self.durations = durations
        self.calls = 0

    def __call__(self, command, **kwargs):
        self.calls += 1
        output = Path(command[command.index("--output") + 1])
        if not self.durations or self.calls > len(self.durations):
            return subprocess.CompletedProcess(command, 1, "", "no injected duration")
        duration = self.durations[self.calls - 1]
        output.write_text(GCODE.replace("18m 4s", duration).replace("18m 46s", duration), encoding="utf-8")
        return subprocess.CompletedProcess(command, 0, "", "")


class OptimizerTests(unittest.TestCase):
    def _run(self, times: dict[str, str], intent: str = "fast-structural"):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            fixture = _Fixture(root)
            fixture.add_part("Widget/Bracket", intent=_intent(
                orientation={
                    "contact_face": "-Z",
                    "rationale": "flat",
                    "allowed_alternatives": ["+Z"],
                },
            ))
            index_path = fixture.write_index()
            manifest = fixture.manifest()
            presets = _presets(_config_root(root))
            runner = FakeRunner(durations=times)
            report = prusaslicer_optimize.optimize(
                manifest, index_path, presets, intent=intent, runner=runner, executable="/usr/bin/false", gcode_format="ascii",
            )
            return report

    def test_candidates_rank_by_injected_time(self) -> None:
        # 4 variants x declared faces (-Z primary + +Z alternative) = 8 slices.
        # First four calls hit the -Z baseline/variants in order; inject slow
        # durations there and fast ones after, so every +Z candidate outranks
        # every -Z one under the fast-structural objective.
        report = self._run(["30m 0s"] * 4 + ["10m 0s"] * 4)
        self.assertTrue(report["ok"], json.dumps(report.get("failure"), default=str))
        ok_entries = [entry for entry in report["ranking"] if entry["ok"]]
        self.assertEqual(8, len(ok_entries))
        # The four fastest entries carry the 10-minute injections.
        self.assertEqual([600.0] * 4, [entry["time_s"] for entry in report["ranking"][:4]])
        top_faces = {entry["contact_face"] for entry in report["ranking"][:4]}
        self.assertEqual({"+Z"}, top_faces)
        self.assertEqual("+Z", report["best"]["contact_face"])

    def test_all_fail_is_structured_failure_not_crash(self) -> None:
        report = self._run([])
        self.assertFalse(report["ok"])
        self.assertEqual("all_candidates_failed", report["outcome"])
        self.assertEqual(8, len(report["ranking"]))
        for entry in report["ranking"]:
            self.assertFalse(entry["ok"])
            self.assertIn("failure", entry)

    def test_six_faces_times_variants_is_bounded_to_the_cap(self) -> None:
        # F2: no declared alternatives means six faces x four variants = 24,
        # above the cap. The matrix is bounded BEFORE expansion: every face
        # keeps its baseline row, later variants are dropped deterministically,
        # and every drop is recorded in the report.
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            fixture = _Fixture(root)
            fixture.add_part("Widget/Bracket")  # default intent: no alternatives
            report = prusaslicer_optimize.optimize(
                fixture.manifest(), fixture.write_index(), _presets(_config_root(root)),
                runner=FakeRunner([]), executable="/usr/bin/false", gcode_format="ascii",
            )
            self.assertEqual(prusaslicer_optimize.MAX_CANDIDATES, report["candidate_count"])
            kept = {entry["candidate_id"] for entry in report["ranking"]}
            # Six faces, each keeping its baseline variant.
            baselines = [cid for cid in kept if cid.endswith(":baseline")]
            self.assertEqual(6, len(baselines))
            dropped = report["dropped_candidates"]
            self.assertEqual(24 - prusaslicer_optimize.MAX_CANDIDATES, len(dropped))
            self.assertEqual(sorted(dropped), sorted(set(dropped)), "dropped ids must be unique")
            for face in ("+X", "+Y", "+Z", "-X", "-Y", "-Z"):
                self.assertIn(f"Widget/Bracket:{face}:baseline", kept)

    def test_fine_detail_ranks_finer_layers_above_coarser_at_equal_time(self) -> None:
        # F4: layer term must prefer SMALLER heights under ascending sort.
        statistics = {"estimated_printing_time_normal": "10m", "total_filament_used_g": 3.9}
        fine = prusaslicer_optimize.score_candidate("fine-detail", statistics, 0.12)
        coarse = prusaslicer_optimize.score_candidate("fine-detail", statistics, 0.28)
        self.assertLess(fine, coarse)
        # Baselines without an override get the neutral mid-value so they do
        # not beat explicit detail variants for free.
        baseline = prusaslicer_optimize.score_candidate("fine-detail", statistics, None)
        self.assertLess(fine, baseline)
        self.assertLess(baseline, coarse)

    def test_proxy_penalty_orders_equal_cost_candidates_by_overhang(self) -> None:
        # F5: proxies feed the score -- equal time/mass, different overhang,
        # rank in proxy order.
        statistics = {"estimated_printing_time_normal": "10m", "total_filament_used_g": 3.9}
        low = prusaslicer_optimize.proxy_penalty(
            "fast-structural",
            {"overhang_area_fraction": 0.05, "max_unsupported_span_mm": 2.0, "vertical_wall_fraction": 0.5},
        )
        high = prusaslicer_optimize.proxy_penalty(
            "fast-structural",
            {"overhang_area_fraction": 0.40, "max_unsupported_span_mm": 20.0, "vertical_wall_fraction": 0.5},
        )
        self.assertLess(
            prusaslicer_optimize.score_candidate("fast-structural", statistics, None, low),
            prusaslicer_optimize.score_candidate("fast-structural", statistics, None, high),
        )
        # Vertical-wall fraction only penalizes fine-detail intents.
        structural = prusaslicer_optimize.proxy_penalty(
            "fast-structural",
            {"overhang_area_fraction": 0.0, "max_unsupported_span_mm": 0.0, "vertical_wall_fraction": 0.9},
        )
        detail = prusaslicer_optimize.proxy_penalty(
            "fine-detail",
            {"overhang_area_fraction": 0.0, "max_unsupported_span_mm": 0.0, "vertical_wall_fraction": 0.9},
        )
        self.assertEqual(0.0, structural)
        self.assertGreater(detail, 0.0)

    def test_drift_guard_aborts_naming_the_preset(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            fixture = _Fixture(root)
            # Three declared faces x four variants = 12 candidates, exactly at
            # the cap, so the drift fires before slicing rather than the cap.
            fixture.add_part("Widget/Bracket", intent=_intent(
                orientation={
                    "contact_face": "-Z",
                    "rationale": "flat",
                    "allowed_alternatives": ["+Z", "+X"],
                },
            ))
            index_path = fixture.write_index()
            manifest = fixture.manifest()
            config = _config_root(root)
            presets = _presets(config)
            original_hashes = prusaslicer_optimize.preset_hashes

            def drift_once(presets_arg):
                hashes = original_hashes(presets_arg)
                printer_ini = next((config / "printer").glob("*.ini"))
                printer_ini.write_text(printer_ini.read_text() + "\n# drifted\n", encoding="utf-8")
                drift_once.calls += 1
                return hashes

            drift_once.calls = 0
            with unittest.mock.patch.object(prusaslicer_optimize, "preset_hashes", drift_once):
                report = prusaslicer_optimize.optimize(
                    manifest, index_path, presets, runner=FakeRunner([]), executable="/usr/bin/false", gcode_format="ascii",
                )
            self.assertFalse(report["ok"])
            self.assertEqual("preset_drift", report["outcome"])
            self.assertIn("printer", report["drifted_presets"])


if __name__ == "__main__":
    unittest.main()
