from __future__ import annotations

import hashlib
from pathlib import Path
import stat
import subprocess
import tempfile
import unittest
from unittest import mock

from fusion_design import prusaslicer_slice
from fusion_design.prusaslicer_project import ResolvedPresets
from fusion_design.prusaslicer_slice import (
    IncompleteProfileSetError,
    parse_gcode_statistics,
    require_complete_profile_set,
    resolve_executable,
    slice_project,
)


# Captured verbatim from a real PrusaSlicer 2.9.6 run on this host
# (Original Prusa XL, --binary-gcode=0). The five columns are the five tools.
GCODE = """; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 04:32:04 UTC

G1 X10 Y10 E1
; filament used [mm] = 1284.99, 0.00, 0.00, 0.00, 0.00
; filament used [cm3] = 3.09, 0.00, 0.00, 0.00, 0.00
; filament used [g] = 3.93, 0.00, 0.00, 0.00, 0.00
; total filament used [g] = 3.93
; total filament cost = 0.12
; estimated printing time (normal mode) = 18m 4s
; estimated printing time (silent mode) = 18m 46s
"""

PRESETS = ResolvedPresets(
    printer="Original Prusa XL - 5T Input Shaper HF0.4 & HF0.6 nozzles",
    filament="Prusament PETG @XL HF0.4",
    print_settings="0.20mm SPEED @XLIS HF0.4",
    config_root="/config/root",
)


class _Runner:
    """Records every command it is asked to run; never starts a process."""

    def __init__(self, returncode: int = 0, stdout: str = "", stderr: str = "", gcode: str | None = GCODE):
        self.calls: list[list[str]] = []
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr
        self.gcode = gcode

    def __call__(self, command, **kwargs):
        self.calls.append(list(command))
        if self.gcode is not None and "--output" in command:
            Path(command[command.index("--output") + 1]).write_text(self.gcode, encoding="utf-8")
        return subprocess.CompletedProcess(command, self.returncode, self.stdout, self.stderr)


def _fake_slicer(root: Path, exit_code: int = 0) -> Path:
    """A stand-in binary that emits canned G-code. The real slicer is never run in tests."""
    script = root / f"fake-slicer-{exit_code}"
    script.write_text(
        "#!/usr/bin/env python3\n"
        "import sys\n"
        "argv = sys.argv[1:]\n"
        "if '--output' in argv:\n"
        "    open(argv[argv.index('--output') + 1], 'w').write('''" + GCODE + "''')\n"
        f"sys.exit({exit_code})\n",
        encoding="utf-8",
    )
    script.chmod(script.stat().st_mode | stat.S_IXUSR)
    return script


def _project(root: Path) -> Path:
    path = root / "project.3mf"
    path.write_bytes(b"PK\x03\x04 pretend project")
    return path


class IncompleteProfileSetTests(unittest.TestCase):
    """The actual defect: a partial profile set is what segfaults PrusaSlicer."""

    def test_each_missing_kind_is_refused_by_name(self) -> None:
        complete = {"printer": "P", "print": "Q", "filament": "M"}
        for kind in ("printer", "print", "filament"):
            for empty in (None, "", "   "):
                with self.subTest(kind=kind, empty=empty):
                    partial = {**complete, kind: empty}
                    with self.assertRaises(IncompleteProfileSetError) as caught:
                        require_complete_profile_set(partial)
                    self.assertIn(kind, str(caught.exception))
                    self.assertIn("139", str(caught.exception))

    def test_complete_set_is_returned_stripped(self) -> None:
        self.assertEqual(
            {"printer": "P", "print": "Q", "filament": "M"},
            require_complete_profile_set({"printer": " P ", "print": "Q", "filament": "M"}),
        )

    def test_resolved_presets_are_accepted(self) -> None:
        self.assertEqual(
            {
                "printer": PRESETS.printer,
                "print": PRESETS.print_settings,
                "filament": PRESETS.filament,
            },
            require_complete_profile_set(PRESETS),
        )

    def test_nothing_is_executed_when_the_set_is_incomplete(self) -> None:
        runner = _Runner()
        with tempfile.TemporaryDirectory() as temporary:
            project = _project(Path(temporary))
            with self.assertRaises(IncompleteProfileSetError):
                slice_project(
                    project,
                    {"printer": "P", "print": "Q"},
                    executable=project,  # any existing file; must never be reached
                    runner=runner,
                )
        self.assertEqual([], runner.calls)


class ExecutableDiscoveryTests(unittest.TestCase):
    def test_explicit_path_wins_and_a_missing_one_is_not_substituted(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            binary = Path(temporary) / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            self.assertEqual(binary, resolve_executable(binary))
            self.assertIsNone(resolve_executable(Path(temporary) / "absent"))

    def test_bundle_then_path_then_none(self) -> None:
        with mock.patch.object(prusaslicer_slice, "BUNDLE_EXECUTABLE") as bundle:
            bundle.is_file.return_value = True
            self.assertIs(bundle, resolve_executable())
            bundle.is_file.return_value = False
            with mock.patch.object(prusaslicer_slice.shutil, "which", return_value="/usr/bin/prusa-slicer"):
                self.assertEqual(Path("/usr/bin/prusa-slicer"), resolve_executable())
            with mock.patch.object(prusaslicer_slice.shutil, "which", return_value=None):
                self.assertIsNone(resolve_executable())

    def test_unavailable_slicer_is_a_structured_result_not_a_crash(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            project = _project(Path(temporary))
            with mock.patch.object(prusaslicer_slice, "resolve_executable", return_value=None):
                result = slice_project(project, PRESETS, runner=_Runner())
        self.assertTrue(result["supported"])
        self.assertFalse(result["attempted"])
        self.assertFalse(result["ok"])
        self.assertIn("No PrusaSlicer executable was found", result["reason"])


class StatisticsParsingTests(unittest.TestCase):
    def test_real_footer_is_parsed(self) -> None:
        statistics, absent = parse_gcode_statistics(GCODE)
        self.assertEqual([], absent)
        self.assertEqual("18m 4s", statistics["estimated_printing_time_normal"])
        self.assertEqual("18m 46s", statistics["estimated_printing_time_silent"])
        self.assertEqual([1284.99, 0.0, 0.0, 0.0, 0.0], statistics["filament_used_mm"])
        self.assertEqual(1284.99, statistics["filament_used_mm_total"])
        self.assertEqual(3.93, statistics["filament_used_g_total"])
        self.assertEqual(3.93, statistics["total_filament_used_g"])
        self.assertEqual(3.09, statistics["filament_used_cm3_total"])

    def test_absent_and_unparseable_fields_are_reported_not_guessed(self) -> None:
        statistics, absent = parse_gcode_statistics(
            "; filament used [g] = n/a\n; estimated printing time (normal mode) = 1h 2m\n"
        )
        self.assertEqual({"estimated_printing_time_normal": "1h 2m"}, statistics)
        self.assertIn("filament_used_g", absent)
        self.assertIn("filament_used_mm", absent)
        self.assertIn("total_filament_used_g", absent)

    def test_binary_gcode_yields_no_invented_numbers(self) -> None:
        statistics, absent = parse_gcode_statistics("GCDE\x00\x01Producer=PrusaSlicer 2.9.6")
        self.assertEqual({}, statistics)
        self.assertEqual(len(prusaslicer_slice._STATISTIC_KEYS), len(absent))


class SliceInvocationTests(unittest.TestCase):
    def test_only_the_resolved_binary_is_invoked_with_the_whole_profile_set(self) -> None:
        runner = _Runner()
        with tempfile.TemporaryDirectory() as temporary:
            project = _project(Path(temporary))
            binary = Path(temporary) / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            slice_project(project, PRESETS, executable=binary, runner=runner)

        self.assertEqual(1, len(runner.calls))
        command = runner.calls[0]
        self.assertEqual(str(binary), command[0])
        for flag, value in (
            ("--printer-profile", PRESETS.printer),
            ("--print-profile", PRESETS.print_settings),
            ("--material-profile", PRESETS.filament),
        ):
            self.assertIn(flag, command)
            self.assertEqual(value, command[command.index(flag) + 1])
        # Presets were resolved against this root, so slicing uses the same one.
        self.assertEqual(PRESETS.config_root, command[command.index("--datadir") + 1])
        self.assertIn("--binary-gcode=0", command)
        self.assertTrue(all(isinstance(argument, str) for argument in command))

    def test_success_binds_statistics_to_project_and_gcode_evidence(self) -> None:
        runner = _Runner(stdout="Slicing result exported to project.gcode\n")
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, executable=binary, runner=runner)

            self.assertTrue(result["ok"])
            self.assertEqual(0, result["exit_code"])
            self.assertEqual(hashlib.sha256(project.read_bytes()).hexdigest(), result["project_sha256"])
            gcode = Path(result["gcode_path"])
            self.assertEqual(hashlib.sha256(gcode.read_bytes()).hexdigest(), result["gcode_sha256"])
            self.assertEqual(gcode.stat().st_size, result["gcode_byte_size"])
        self.assertEqual("PrusaSlicer 2.9.6", result["slicer_version"])
        self.assertEqual(str(binary), result["executable"])
        self.assertEqual(
            {"printer": PRESETS.printer, "print": PRESETS.print_settings, "filament": PRESETS.filament},
            result["presets"],
        )
        self.assertEqual("18m 4s", result["statistics"]["estimated_printing_time_normal"])
        self.assertEqual([], result["warnings"])

    def test_segfault_exit_is_a_structured_failure_with_diagnostics(self) -> None:
        runner = _Runner(returncode=139, stderr="boom\n", gcode=None)
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, executable=binary, runner=runner)
            self.assertFalse((root / "project.gcode").exists())

        self.assertFalse(result["ok"])
        self.assertTrue(result["attempted"])
        self.assertEqual(139, result["exit_code"])
        self.assertIn("SIGSEGV", result["failure"])
        self.assertEqual("boom", result["stderr_tail"])
        self.assertNotIn("statistics", result)

    def test_exit_zero_without_gcode_is_still_a_failure(self) -> None:
        runner = _Runner(gcode=None, stderr="nothing written")
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, executable=binary, runner=runner)
        self.assertFalse(result["ok"])
        self.assertIn("wrote no G-code", result["failure"])
        self.assertNotIn("statistics", result)

    def test_timeout_is_reported_and_cannot_hang(self) -> None:
        def timing_out(command, **kwargs):
            self.assertEqual(7, kwargs["timeout"])
            raise subprocess.TimeoutExpired(command, kwargs["timeout"])

        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, executable=binary, timeout=7, runner=timing_out)

        self.assertFalse(result["ok"])
        self.assertIsNone(result["exit_code"])
        self.assertIn("did not finish within 7 seconds", result["failure"])
        self.assertNotIn("statistics", result)

    def test_warnings_are_collected_from_slicer_output(self) -> None:
        runner = _Runner(stderr="WARNING: object is too tall\nfine\n")
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            result = slice_project(project, PRESETS, executable=binary, runner=runner)
        self.assertEqual(["WARNING: object is too tall"], result["warnings"])

    def test_existing_gcode_is_never_overwritten(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            project = _project(root)
            (root / "project.gcode").write_text("earlier", encoding="utf-8")
            binary = root / "PrusaSlicer"
            binary.write_text("", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "Refusing to overwrite"):
                slice_project(project, PRESETS, executable=binary, runner=_Runner())
            self.assertEqual("earlier", (root / "project.gcode").read_text(encoding="utf-8"))


class RealSubprocessTests(unittest.TestCase):
    """Exercises the actual subprocess path against a stand-in, never real PrusaSlicer."""

    def test_real_run_parses_statistics(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            result = slice_project(
                _project(root), PRESETS, executable=_fake_slicer(root), datadir=root
            )
        self.assertTrue(result.get("ok"), result)
        self.assertEqual(3.93, result["statistics"]["total_filament_used_g"])
        self.assertEqual("PrusaSlicer 2.9.6", result["slicer_version"])

    def test_real_non_zero_exit_fails_closed(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            result = slice_project(
                _project(root), PRESETS, executable=_fake_slicer(root, exit_code=139), datadir=root
            )
        self.assertFalse(result["ok"])
        self.assertEqual(139, result["exit_code"])
        self.assertIn("SIGSEGV", result["failure"])


class ExecutionIsConfinedTests(unittest.TestCase):
    """Slicing needs subprocess, so the no-execution guarantee moved rather than vanished."""

    def test_prusaslicer_slice_is_the_only_module_that_can_start_a_process(self) -> None:
        from test_prusaslicer_project import process_execution_offenses

        package = Path(prusaslicer_slice.__file__).parent
        offenders = {
            module.name
            for module in sorted(package.glob("*.py"))
            if process_execution_offenses(module.read_text(encoding="utf-8"))
        }
        self.assertEqual({"prusaslicer_slice.py"}, offenders)

    def test_the_command_is_an_argument_list_and_never_a_shell_string(self) -> None:
        source = Path(prusaslicer_slice.__file__).read_text(encoding="utf-8")
        self.assertNotIn("shell=True", source)
        self.assertNotIn("subprocess.Popen", source)
        self.assertNotIn("os.system", source)


if __name__ == "__main__":
    unittest.main()
