from __future__ import annotations

from pathlib import Path
import tempfile
import unittest

from fusion_design.gcode_audit import (
    MAX_ACTIVE_TOOLS,
    MAX_LINE_BYTES,
    MAX_TOOL_EVENTS,
    MAX_TOOL_ID,
    audit_gcode,
)


class GcodeAuditTests(unittest.TestCase):
    def _audit(self, text: str):
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "slice.gcode"
            path.write_text(text, encoding="utf-8")
            return audit_gcode(path)

    def test_single_and_repeated_tool_events_are_observed(self) -> None:
        result = self._audit("; generated by PrusaSlicer 2.9.6\nT0\nT0 ; same tool\n")
        self.assertTrue(result["available"])
        self.assertEqual([{"line": 2, "tool": 0}, {"line": 3, "tool": 0}], result["tool_events"])
        self.assertEqual([0], result["active_tools"])
        self.assertEqual(2, result["tool_event_count"])
        self.assertFalse(result["tool_events_truncated"])
        self.assertEqual(0, result["tool_change_count"])

    def test_alternating_tools_count_only_changes(self) -> None:
        result = self._audit("; generated by PrusaSlicer 2.9.6\nT0\nT1\nT2 ; comment\nT2\nT0\n")
        self.assertEqual([0, 1, 2], result["active_tools"])
        self.assertEqual(3, result["tool_change_count"])
        self.assertEqual([2, 3, 4, 5, 6], [event["line"] for event in result["tool_events"]])

    def test_comments_and_malformed_commands_are_ignored(self) -> None:
        result = self._audit(";FLAVOR:Marlin2\n; T1\nG1 X1 ; T2\nT1 G1\nTT3\nT4 ; real\n")
        self.assertEqual([{"line": 6, "tool": 4}], result["tool_events"])

    def test_final_line_without_newline_is_still_complete(self) -> None:
        result = self._audit("; generated by PrusaSlicer 2.9.6\nT0\nT1")
        self.assertEqual([{"line": 2, "tool": 0}, {"line": 3, "tool": 1}], result["tool_events"])

    def test_chunk_boundary_and_middle_of_large_file_are_scanned(self) -> None:
        text = ";FLAVOR:Marlin2\n" + "G1 X0\n" * 20000 + "T3\n" + "G1 X1\n" * 20000 + "T1\n"
        result = self._audit(text)
        self.assertTrue(result["available"])
        self.assertEqual([1, 3], result["active_tools"])
        self.assertEqual(1, result["tool_change_count"])
        self.assertEqual([20002, 40003], [event["line"] for event in result["tool_events"]])

    def test_unknown_flavor_marker_makes_metric_unavailable(self) -> None:
        result = self._audit("; FLAVOR:unknown\nT0\n")
        self.assertFalse(result["available"])
        self.assertIsNone(result["active_tools"])
        self.assertIsNone(result["tool_change_count"])
        self.assertEqual([], result["tool_events"])

    def test_known_text_flavor_is_compatible(self) -> None:
        result = self._audit(";FLAVOR:Marlin2\nT0\n")
        self.assertTrue(result["available"])
        self.assertEqual("marlin2", result["flavor"])

    def test_unmarked_file_makes_metric_unavailable(self) -> None:
        result = self._audit("T0\n")
        self.assertFalse(result["available"])
        self.assertIn("producer marker", result["reason"])

    def test_recognized_producer_establishes_standard_text_flavor(self) -> None:
        for producer in ("PrusaSlicer", "SuperSlicer"):
            with self.subTest(producer=producer):
                result = self._audit(f"; generated by {producer} 2.9.6\nT0\n")
                self.assertTrue(result["available"])
                self.assertEqual("standard_prusa_text", result["flavor"])

    def test_conflicting_producer_evidence_is_unavailable(self) -> None:
        result = self._audit(
            "; generated by PrusaSlicer 2.9.6\n; generated by SuperSlicer 2.5.0\nT0\n"
        )
        self.assertFalse(result["available"])
        self.assertIn("Conflicting G-code producers", result["reason"])

    def test_oversized_and_out_of_range_tool_ids_are_unavailable(self) -> None:
        for identifier in ("9" * 5000, str(MAX_TOOL_ID + 1)):
            with self.subTest(length=len(identifier)):
                result = self._audit(f"; generated by PrusaSlicer 2.9.6\nT{identifier}\n")
                self.assertFalse(result["available"])
                self.assertIn("supported maximum", result["reason"])

    def test_distinct_active_tools_are_bounded(self) -> None:
        commands = "".join(f"T{tool}\n" for tool in range(MAX_ACTIVE_TOOLS + 1))
        result = self._audit("; generated by PrusaSlicer 2.9.6\n" + commands)
        self.assertFalse(result["available"])
        self.assertIn(f"More than {MAX_ACTIVE_TOOLS}", result["reason"])

    def test_event_list_is_bounded(self) -> None:
        result = self._audit(
            "; generated by PrusaSlicer 2.9.6\n" + "T0\n" * (MAX_TOOL_EVENTS + 1)
        )
        self.assertTrue(result["available"])
        self.assertEqual(MAX_TOOL_EVENTS + 1, result["tool_event_count"])
        self.assertEqual(MAX_TOOL_EVENTS, len(result["tool_events"]))
        self.assertTrue(result["tool_events_truncated"])

    def test_line_byte_limit_counts_the_newline(self) -> None:
        accepted = "T0" + " " * (MAX_LINE_BYTES - 3) + "\n"
        result = self._audit("; generated by PrusaSlicer 2.9.6\n" + accepted)
        self.assertTrue(result["available"])

        refused = "T0" + " " * (MAX_LINE_BYTES - 2) + "\n"
        result = self._audit("; generated by PrusaSlicer 2.9.6\n" + refused)
        self.assertFalse(result["available"])
        self.assertIn("exceeded", result["reason"])


if __name__ == "__main__":
    unittest.main()
