"""Tests for the .bgcode container reader (pybgcode adapter).

The reader delegates GCDE containers to the official pybgcode binding; these
tests cover the passthrough paths unconditionally and the binary paths
skipUnless pybgcode is importable, so the suite still passes on machines
without the optional wheel.
"""

from __future__ import annotations

import gzip
import importlib.util
from pathlib import Path
import tempfile
import unittest
from unittest import mock

from fusion_design.prusaslicer_bgcode import BgcodeError, read_bgcode


HAS_PYBGCODE = importlib.util.find_spec("pybgcode") is not None

GCODE = (
    "; generated by PrusaSlicer 2.9.6 on 2026-08-19 at 04:32:04 UTC\n"
    "G21\nG90\nG1 X10 Y10 F1200\n"
    "; filament used [g] = 3.93\n"
    "; total filament used [g] = 3.93\n"
    "; prusaslicer_config = begin\nlayer_height = 0.2\n; prusaslicer_config = end\n"
)


class PassthroughTests(unittest.TestCase):
    """Paths that never need pybgcode."""

    def test_plain_gzip_stream_round_trips(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.gcode"
            path.write_bytes(gzip.compress(GCODE.encode()))
            self.assertEqual(GCODE, read_bgcode(path))

    def test_plain_text_passthrough_is_refused_as_not_bgcode(self) -> None:
        # Plain text passes through as text (the common case for a .gcode
        # file arriving at read_bgcode by suffix confusion).
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.gcode"
            path.write_bytes(b"plain text\n")
            self.assertEqual("plain text\n", read_bgcode(path))

    def test_corrupt_gzip_stream_is_a_named_failure(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            path = Path(temporary) / "print.gcode"
            path.write_bytes(b"\x1f\x8b not really gzip")
            with self.assertRaisesRegex(BgcodeError, "Corrupt gzip stream"):
                read_bgcode(path)


@unittest.skipUnless(HAS_PYBGCODE, "pybgcode optional binding is not installed")
class PybgcodeContainerTests(unittest.TestCase):
    """Binary-container paths through the official binding."""

    def _binary_container(self, directory: Path, text: str = GCODE) -> Path:
        """A real .bgcode built by pybgcode itself from ascii G-code."""
        import pybgcode

        ascii_path = directory / "source.gcode"
        binary_path = directory / "print.bgcode"
        ascii_path.write_text(text, encoding="utf-8")
        source = pybgcode.open(str(ascii_path), "r")
        target = pybgcode.open(str(binary_path), "w")
        try:
            result = pybgcode.from_ascii_to_binary(source, target)
        finally:
            pybgcode.close(source)
            pybgcode.close(target)
        assert result == pybgcode.EResult.Success, result
        return binary_path

    def test_container_round_trips_through_the_official_binding(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            binary = self._binary_container(Path(temporary))
            decoded = read_bgcode(binary)
            self.assertIn("; total filament used [g] = 3.93", decoded)

    def test_missing_pybgcode_binding_is_a_named_failure(self) -> None:
        # Without Node.js a GCDE file is a named error naming what is missing.
        with tempfile.TemporaryDirectory() as temporary:
            binary = self._binary_container(Path(temporary))
            with mock.patch("shutil.which", return_value=None):
                with self.assertRaisesRegex(BgcodeError, "Node.js"):
                    read_bgcode(binary)


if __name__ == "__main__":
    unittest.main()
